#!/usr/bin/env python3
"""Generate the extractor-probe config from the SHIPPED bundle.

The probe compares the shipped extractor prompt against candidates that differ
from it by a known edit. Freezing a copy of the shipped prompt in a committed
yaml would work exactly once: the day the real prompt changes, the probe would
go on comparing against a prompt nobody runs, and would still print a number.

So the candidates are DERIVED here, at generation time, from
bundles/memory/loomcycle.yaml -- and the run fails loudly if the text they edit
is no longer there, rather than silently measuring an unedited prompt. The
shipped arm is `memory/extractor` itself and is never copied at all.

    python3 bench/synthesis/make_probe_config.py   # writes extractor-probe.yaml
"""
import os, sys, yaml

HERE = os.path.dirname(os.path.abspath(__file__))
BUNDLE = os.path.join(HERE, "..", "..", "bundles", "memory", "loomcycle.yaml")
OUT = os.path.join(HERE, "extractor-probe.yaml")

# The extractor prompt's ceiling is enforced AFTER {{memory:ontology}} expands,
# so a candidate has to be sized the same way or it passes here and fails the
# suite. 533 is the base seed's rendered length (internal/memory RenderOntology);
# a tenant with its own confirmed types renders longer, which is the operator's
# choice and not what this bounds.
ONTOLOGY_CHARS = 533
MAX_CHARS = 2600
PLACEHOLDER = "{{memory:ontology}}"


def effective(prompt):
    return len(prompt) - len(PLACEHOLDER) + ONTOLOGY_CHARS


# The fix is SHIPPED now, so the probe runs the other way round: the control is
# derived by REVERSING the edit out of the current prompt. Same drift protection,
# opposite direction -- the arm that must not be a frozen copy is whichever one
# is not `memory/extractor` itself.
TEMPLATE_NOW = ('[{"text": "...", "class": "..."}] when it names no one thing — or\n'
                '[{"text": "...", "class": "...", "type": "...", "subject": "...", '
                '"also_about": ["..."]}]')
TEMPLATE_WAS = ('[{"text": "...", "class": "...", "type": "...", "subject": "..."}]\n'
                '— or [{"text": "...", "class": "..."}] when it names no one thing.')
PROSE_NOW = ('Others it names go in `also_about`, never alone: "Dave works at the\n'
             'shop" is subject Dave, also_about ["the shop"].')
PROSE_WAS = ('A fact that HAS a subject and names others adds `also_about`: "Dave works\n'
             'at the shop": subject Dave, also_about ["the shop"]. Never alone.')


def edit(prompt, pairs):
    out = prompt
    for old, new in pairs:
        if old not in out:
            sys.exit("make_probe_config: the shipped prompt no longer contains:\n%r\n"
                     "The probe would have measured an UNEDITED prompt against itself. "
                     "Update the edit to match the current prompt." % old)
        out = out.replace(old, new)
    return out


def main():
    bundle = yaml.safe_load(open(BUNDLE))
    shipped = bundle["agents"]["memory/extractor"]["system_prompt"]

    variants = {
        # The prompt as it was before the also_about fix: the field absent from the
        # JSON template, the prose in its old form. This is the control the shipped
        # prompt is measured against.
        "db2/ext-prefix": edit(shipped, [(TEMPLATE_NOW, TEMPLATE_WAS),
                                         (PROSE_NOW, PROSE_WAS)]),
        # The template field WITHOUT the reordering that restored the
        # invented-entity guarantee -- kept because it separates "the field raises
        # the chain rate" from "the order keeps entity invention down".
        "db2/ext-noreorder": edit(shipped, [(TEMPLATE_NOW, TEMPLATE_WAS)]),
    }

    # ⚠️ THE SHIPPED ARM HAS TO BE PINNED TOO. `memory/extractor` ships with no
    # `sampling:` block, so leaving it alone measures an UNPINNED arm against
    # pinned candidates -- a coin against a point. Its rate swung 38/24/17% across
    # runs of the SAME prompt before this was noticed. Sampling is overridden here
    # and the PROMPT is not, so the arm is still the shipped prompt.
    agents = {"memory/extractor": {"sampling": {"temperature": 0, "seed": 7}}}
    for name, prompt in variants.items():
        agents[name] = {
            "tier": "middle", "effort": "low",
            "tools": [], "skills": ["-*"], "disable_context": True,
            # Pinned: an unpinned arm measures a coin, which is how the extraction
            # gate stayed stuck for weeks.
            "sampling": {"temperature": 0, "seed": 7},
            "system_prompt": prompt,
        }
        print("%-20s static %4d  (control arm; the ceiling binds the SHIPPED prompt)"
              % (name, len(prompt)))

    with open(OUT, "w") as f:
        f.write("# GENERATED by bench/synthesis/make_probe_config.py — do not edit.\n"
                "# Candidates are derived from bundles/memory/loomcycle.yaml so they\n"
                "# cannot drift from the prompt that actually ships.\n")
        yaml.safe_dump({"agents": agents}, f, sort_keys=False, width=100,
                       default_flow_style=False)
    print("wrote", OUT)


if __name__ == "__main__":
    main()
