#!/usr/bin/env python3
"""Generate the extractor-probe config from the SHIPPED bundle.

The probe compares the shipped extractor prompt against candidates that differ
from it by a known edit. Freezing a copy of the shipped prompt in a committed
yaml would work exactly once: the day the real prompt changes, the probe would
go on comparing against a prompt nobody runs, and would still print a number.

So the candidates are DERIVED here, at generation time, from
bundles/memory/loomcycle.yaml -- and the run fails loudly if the text they edit
is no longer there, rather than silently measuring an unedited prompt. The
shipped arm is `memory/extractor` itself and is never copied at all.

    python3 bench/synthesis/make_probe_config.py   # writes extractor-probe.yaml
"""
import os, sys, yaml

HERE = os.path.dirname(os.path.abspath(__file__))
BUNDLE = os.path.join(HERE, "..", "..", "bundles", "memory", "loomcycle.yaml")
OUT = os.path.join(HERE, "extractor-probe.yaml")

# The extractor prompt's ceiling is enforced AFTER {{memory:ontology}} expands,
# so a candidate has to be sized the same way or it passes here and fails the
# suite. 533 is the base seed's rendered length (internal/memory RenderOntology);
# a tenant with its own confirmed types renders longer, which is the operator's
# choice and not what this bounds.
ONTOLOGY_CHARS = 533
MAX_CHARS = 2600
PLACEHOLDER = "{{memory:ontology}}"


def effective(prompt):
    return len(prompt) - len(PLACEHOLDER) + ONTOLOGY_CHARS


TEMPLATE_OLD = '[{"text": "...", "class": "...", "type": "...", "subject": "..."}]'
TEMPLATE_NEW = ('[{"text": "...", "class": "...", "type": "...", "subject": "...", '
                '"also_about": ["..."]}]')
PROSE_OLD = ('A fact that HAS a subject and names others adds `also_about`: "Dave works\n'
             'at the shop": subject Dave, also_about ["the shop"]. Never alone.')
# Shorter, and both constraints survive: additive to a subject, never without one.
PROSE_NEW = ('Others it names go in `also_about`, never without a subject: "Dave works\n'
             'at the shop" is subject Dave, also_about ["the shop"].')


def edit(prompt, pairs):
    out = prompt
    for old, new in pairs:
        if old not in out:
            sys.exit("make_probe_config: the shipped prompt no longer contains:\n%r\n"
                     "The probe would have measured an UNEDITED prompt against itself. "
                     "Update the edit to match the current prompt." % old)
        out = out.replace(old, new)
    return out


def main():
    bundle = yaml.safe_load(open(BUNDLE))
    shipped = bundle["agents"]["memory/extractor"]["system_prompt"]

    variants = {
        # The field named in the JSON template, nothing else touched. This is the
        # hypothesis under test and it does NOT fit the ceiling -- kept so the
        # measurement separates "does the template matter" from "does the tightened
        # prose cost anything".
        "db2/ext-candidate": edit(shipped, [(TEMPLATE_OLD, TEMPLATE_NEW)]),
        # The same field, paid for by tightening the prose that introduced it --
        # which is what the size test asks for instead of raising the ceiling.
        "db2/ext-fitted": edit(shipped, [(TEMPLATE_OLD, TEMPLATE_NEW),
                                         (PROSE_OLD, PROSE_NEW)]),
    }

    agents = {}
    for name, prompt in variants.items():
        agents[name] = {
            "tier": "middle", "effort": "low",
            "tools": [], "skills": ["-*"], "disable_context": True,
            # Pinned: an unpinned arm measures a coin, which is how the extraction
            # gate stayed stuck for weeks.
            "sampling": {"temperature": 0, "seed": 7},
            "system_prompt": prompt,
        }
        print("%-20s static %4d  effective %4d  ceiling %d  %s"
              % (name, len(prompt), effective(prompt), MAX_CHARS,
                 "OK" if effective(prompt) <= MAX_CHARS else "OVER THE CEILING"))

    with open(OUT, "w") as f:
        f.write("# GENERATED by bench/synthesis/make_probe_config.py — do not edit.\n"
                "# Candidates are derived from bundles/memory/loomcycle.yaml so they\n"
                "# cannot drift from the prompt that actually ships.\n")
        yaml.safe_dump({"agents": agents}, f, sort_keys=False, width=100,
                       default_flow_style=False)
    print("wrote", OUT)


if __name__ == "__main__":
    main()
