# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import loomcycle_pb2 as loomcycle__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in loomcycle_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LoomcycleStub(object):
    """========================
    Service
    ========================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Run = channel.unary_stream(
                '/loomcycle.v1.Loomcycle/Run',
                request_serializer=loomcycle__pb2.RunRequest.SerializeToString,
                response_deserializer=loomcycle__pb2.Event.FromString,
                _registered_method=True)
        self.Continue = channel.unary_stream(
                '/loomcycle.v1.Loomcycle/Continue',
                request_serializer=loomcycle__pb2.ContinueRequest.SerializeToString,
                response_deserializer=loomcycle__pb2.Event.FromString,
                _registered_method=True)
        self.GetTranscript = channel.unary_unary(
                '/loomcycle.v1.Loomcycle/GetTranscript',
                request_serializer=loomcycle__pb2.GetTranscriptRequest.SerializeToString,
                response_deserializer=loomcycle__pb2.Transcript.FromString,
                _registered_method=True)
        self.GetAgent = channel.unary_unary(
                '/loomcycle.v1.Loomcycle/GetAgent',
                request_serializer=loomcycle__pb2.GetAgentRequest.SerializeToString,
                response_deserializer=loomcycle__pb2.Agent.FromString,
                _registered_method=True)
        self.CancelAgent = channel.unary_unary(
                '/loomcycle.v1.Loomcycle/CancelAgent',
                request_serializer=loomcycle__pb2.CancelAgentRequest.SerializeToString,
                response_deserializer=loomcycle__pb2.CancelAgentResponse.FromString,
                _registered_method=True)
        self.ListUserAgents = channel.unary_unary(
                '/loomcycle.v1.Loomcycle/ListUserAgents',
                request_serializer=loomcycle__pb2.ListUserAgentsRequest.SerializeToString,
                response_deserializer=loomcycle__pb2.ListUserAgentsResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/loomcycle.v1.Loomcycle/Health',
                request_serializer=loomcycle__pb2.HealthRequest.SerializeToString,
                response_deserializer=loomcycle__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.PauseRuntime = channel.unary_unary(
                '/loomcycle.v1.Loomcycle/PauseRuntime',
                request_serializer=loomcycle__pb2.PauseRuntimeRequest.SerializeToString,
                response_deserializer=loomcycle__pb2.PauseRuntimeResponse.FromString,
                _registered_method=True)
        self.ResumeRuntime = channel.unary_unary(
                '/loomcycle.v1.Loomcycle/ResumeRuntime',
                request_serializer=loomcycle__pb2.ResumeRuntimeRequest.SerializeToString,
                response_deserializer=loomcycle__pb2.ResumeRuntimeResponse.FromString,
                _registered_method=True)
        self.GetRuntimeState = channel.unary_unary(
                '/loomcycle.v1.Loomcycle/GetRuntimeState',
                request_serializer=loomcycle__pb2.GetRuntimeStateRequest.SerializeToString,
                response_deserializer=loomcycle__pb2.RuntimeStateResponse.FromString,
                _registered_method=True)
        self.CreateSnapshot = channel.unary_unary(
                '/loomcycle.v1.Loomcycle/CreateSnapshot',
                request_serializer=loomcycle__pb2.CreateSnapshotRequest.SerializeToString,
                response_deserializer=loomcycle__pb2.SnapshotDescriptor.FromString,
                _registered_method=True)
        self.ListSnapshots = channel.unary_unary(
                '/loomcycle.v1.Loomcycle/ListSnapshots',
                request_serializer=loomcycle__pb2.ListSnapshotsRequest.SerializeToString,
                response_deserializer=loomcycle__pb2.ListSnapshotsResponse.FromString,
                _registered_method=True)
        self.GetSnapshot = channel.unary_unary(
                '/loomcycle.v1.Loomcycle/GetSnapshot',
                request_serializer=loomcycle__pb2.GetSnapshotRequest.SerializeToString,
                response_deserializer=loomcycle__pb2.SnapshotEnvelope.FromString,
                _registered_method=True)
        self.ExportSnapshot = channel.unary_unary(
                '/loomcycle.v1.Loomcycle/ExportSnapshot',
                request_serializer=loomcycle__pb2.ExportSnapshotRequest.SerializeToString,
                response_deserializer=loomcycle__pb2.ExportSnapshotResponse.FromString,
                _registered_method=True)
        self.RestoreSnapshot = channel.unary_unary(
                '/loomcycle.v1.Loomcycle/RestoreSnapshot',
                request_serializer=loomcycle__pb2.RestoreSnapshotRequest.SerializeToString,
                response_deserializer=loomcycle__pb2.RestoreSnapshotResponse.FromString,
                _registered_method=True)
        self.DeleteSnapshot = channel.unary_unary(
                '/loomcycle.v1.Loomcycle/DeleteSnapshot',
                request_serializer=loomcycle__pb2.DeleteSnapshotRequest.SerializeToString,
                response_deserializer=loomcycle__pb2.DeleteSnapshotResponse.FromString,
                _registered_method=True)


class LoomcycleServicer(object):
    """========================
    Service
    ========================

    """

    def Run(self, request, context):
        """Run starts a fresh agent run and server-streams its events. One
        request → many Event responses. The stream terminates on EOF when
        the loop reaches its terminal state (done, failed, or cancelled).

        Mirrors POST /v1/runs.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Continue(self, request, context):
        """Continue extends an existing session with a new run. The session's
        prior transcript is replayed into the loop's context; the response
        stream covers only the NEW events from this continuation.

        Mirrors POST /v1/sessions/{id}/messages.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTranscript(self, request, context):
        """GetTranscript returns the full event history for a session,
        ordered by seq. Used by adapters that re-attach to a previously
        started session (e.g. cross-tab sync).

        Mirrors GET /v1/sessions/{id}/transcript.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAgent(self, request, context):
        """GetAgent returns one agent's current status + usage stats. Used
        by adapters polling for completion when the SSE/gRPC stream was
        interrupted (browser tab closed, network blip).

        Mirrors GET /v1/agents/{agent_id}.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelAgent(self, request, context):
        """CancelAgent sets the agent's terminal status to "cancelled" and
        cascades the cancellation to every child via parent_agent_id.

        Mirrors POST /v1/agents/{agent_id}/cancel.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListUserAgents(self, request, context):
        """ListUserAgents enumerates a user's recent agent runs, optionally
        filtered by status.

        Mirrors GET /v1/users/{user_id}/agents.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Health is the liveness probe. Returns build identifier + uptime.

        Mirrors GET /healthz (which is unauthenticated on the HTTP side;
        the gRPC equivalent stays unauthenticated for parity).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PauseRuntime(self, request, context):
        """----- v0.8.17 Pause / Resume / Snapshot (real impls in v0.8.18) -----

        Runtime-wide quiesce + cross-version-portable JSON snapshot. Wire
        shapes mirror the connector.Connector method signatures. Typed
        errors from internal/connector/errors.go map to gRPC codes:
        ErrPauseNotConfigured     → Unavailable (503-equivalent)
        ErrAlreadyPausing         → FailedPrecondition (409-equivalent)
        ErrNotPaused              → FailedPrecondition (409-equivalent)
        ErrSnapshotNotFound       → NotFound (404-equivalent)
        ErrSnapshotTooLarge       → ResourceExhausted (413-equivalent)
        ErrSnapshotVersionTooNew  → FailedPrecondition (422-equivalent)
        ErrSnapshotVersionUnknown → FailedPrecondition (422-equivalent)

        PauseRuntime quiesces the runtime. Idempotent tools cancel
        immediately; non-idempotent + external tools get a grace window
        (default 30 s; max 5 min) then force-cancel. Returns 409-equivalent
        when the runtime is already pausing or paused.

        Mirrors POST /v1/_pause.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResumeRuntime(self, request, context):
        """ResumeRuntime releases the quiesce. Paused runs re-enter their
        loops. Returns 409-equivalent when the runtime is not paused.

        Mirrors POST /v1/_resume.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRuntimeState(self, request, context):
        """GetRuntimeState returns the current quiesce state for dashboards.

        Mirrors GET /v1/_state.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateSnapshot(self, request, context):
        """CreateSnapshot captures running-state into a per-section-semver
        JSON envelope (agent_defs, agent_def_active, memory, channels,
        evaluations, paused_runs, optional interaction_history). Returns
        413-equivalent when the serialised envelope exceeds the configured
        cap (LOOMCYCLE_SNAPSHOT_MAX_BYTES; default 512 MiB).

        Mirrors POST /v1/_snapshots.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSnapshots(self, request, context):
        """ListSnapshots returns metadata for the most-recent snapshots
        (capped at 200). The JSON envelope itself is not included; use
        GetSnapshot / ExportSnapshot to fetch.

        Mirrors GET /v1/_snapshots.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSnapshot(self, request, context):
        """GetSnapshot returns the full envelope including JSON content.
        Distinct from ExportSnapshot, which is operator-facing "where did
        this land on the host" semantics.

        Mirrors GET /v1/_snapshots/{id}.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExportSnapshot(self, request, context):
        """ExportSnapshot returns canonical envelope bytes (raw_json) for a
        snapshot id. Transports that stream large exports use raw_json
        directly; file_path / checksum stay empty unless materialised.

        Mirrors GET /v1/_snapshots/{id}/export.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RestoreSnapshot(self, request, context):
        """RestoreSnapshot restores from a same-instance snapshot_id OR
        cross-instance raw_json. Idempotent: ON CONFLICT DO NOTHING per
        row. Counters in the response reflect rows actually written.
        Returns 422-equivalent on snapshot version newer than reader
        supports.

        Mirrors POST /v1/_snapshots/{id}/restore.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteSnapshot(self, request, context):
        """DeleteSnapshot removes a snapshot. Idempotent — succeeds whether
        or not the row existed.

        Mirrors DELETE /v1/_snapshots/{id}.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LoomcycleServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Run': grpc.unary_stream_rpc_method_handler(
                    servicer.Run,
                    request_deserializer=loomcycle__pb2.RunRequest.FromString,
                    response_serializer=loomcycle__pb2.Event.SerializeToString,
            ),
            'Continue': grpc.unary_stream_rpc_method_handler(
                    servicer.Continue,
                    request_deserializer=loomcycle__pb2.ContinueRequest.FromString,
                    response_serializer=loomcycle__pb2.Event.SerializeToString,
            ),
            'GetTranscript': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTranscript,
                    request_deserializer=loomcycle__pb2.GetTranscriptRequest.FromString,
                    response_serializer=loomcycle__pb2.Transcript.SerializeToString,
            ),
            'GetAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAgent,
                    request_deserializer=loomcycle__pb2.GetAgentRequest.FromString,
                    response_serializer=loomcycle__pb2.Agent.SerializeToString,
            ),
            'CancelAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelAgent,
                    request_deserializer=loomcycle__pb2.CancelAgentRequest.FromString,
                    response_serializer=loomcycle__pb2.CancelAgentResponse.SerializeToString,
            ),
            'ListUserAgents': grpc.unary_unary_rpc_method_handler(
                    servicer.ListUserAgents,
                    request_deserializer=loomcycle__pb2.ListUserAgentsRequest.FromString,
                    response_serializer=loomcycle__pb2.ListUserAgentsResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=loomcycle__pb2.HealthRequest.FromString,
                    response_serializer=loomcycle__pb2.HealthResponse.SerializeToString,
            ),
            'PauseRuntime': grpc.unary_unary_rpc_method_handler(
                    servicer.PauseRuntime,
                    request_deserializer=loomcycle__pb2.PauseRuntimeRequest.FromString,
                    response_serializer=loomcycle__pb2.PauseRuntimeResponse.SerializeToString,
            ),
            'ResumeRuntime': grpc.unary_unary_rpc_method_handler(
                    servicer.ResumeRuntime,
                    request_deserializer=loomcycle__pb2.ResumeRuntimeRequest.FromString,
                    response_serializer=loomcycle__pb2.ResumeRuntimeResponse.SerializeToString,
            ),
            'GetRuntimeState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRuntimeState,
                    request_deserializer=loomcycle__pb2.GetRuntimeStateRequest.FromString,
                    response_serializer=loomcycle__pb2.RuntimeStateResponse.SerializeToString,
            ),
            'CreateSnapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSnapshot,
                    request_deserializer=loomcycle__pb2.CreateSnapshotRequest.FromString,
                    response_serializer=loomcycle__pb2.SnapshotDescriptor.SerializeToString,
            ),
            'ListSnapshots': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSnapshots,
                    request_deserializer=loomcycle__pb2.ListSnapshotsRequest.FromString,
                    response_serializer=loomcycle__pb2.ListSnapshotsResponse.SerializeToString,
            ),
            'GetSnapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSnapshot,
                    request_deserializer=loomcycle__pb2.GetSnapshotRequest.FromString,
                    response_serializer=loomcycle__pb2.SnapshotEnvelope.SerializeToString,
            ),
            'ExportSnapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.ExportSnapshot,
                    request_deserializer=loomcycle__pb2.ExportSnapshotRequest.FromString,
                    response_serializer=loomcycle__pb2.ExportSnapshotResponse.SerializeToString,
            ),
            'RestoreSnapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.RestoreSnapshot,
                    request_deserializer=loomcycle__pb2.RestoreSnapshotRequest.FromString,
                    response_serializer=loomcycle__pb2.RestoreSnapshotResponse.SerializeToString,
            ),
            'DeleteSnapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteSnapshot,
                    request_deserializer=loomcycle__pb2.DeleteSnapshotRequest.FromString,
                    response_serializer=loomcycle__pb2.DeleteSnapshotResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'loomcycle.v1.Loomcycle', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('loomcycle.v1.Loomcycle', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Loomcycle(object):
    """========================
    Service
    ========================

    """

    @staticmethod
    def Run(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/loomcycle.v1.Loomcycle/Run',
            loomcycle__pb2.RunRequest.SerializeToString,
            loomcycle__pb2.Event.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Continue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/loomcycle.v1.Loomcycle/Continue',
            loomcycle__pb2.ContinueRequest.SerializeToString,
            loomcycle__pb2.Event.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTranscript(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loomcycle.v1.Loomcycle/GetTranscript',
            loomcycle__pb2.GetTranscriptRequest.SerializeToString,
            loomcycle__pb2.Transcript.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loomcycle.v1.Loomcycle/GetAgent',
            loomcycle__pb2.GetAgentRequest.SerializeToString,
            loomcycle__pb2.Agent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loomcycle.v1.Loomcycle/CancelAgent',
            loomcycle__pb2.CancelAgentRequest.SerializeToString,
            loomcycle__pb2.CancelAgentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListUserAgents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loomcycle.v1.Loomcycle/ListUserAgents',
            loomcycle__pb2.ListUserAgentsRequest.SerializeToString,
            loomcycle__pb2.ListUserAgentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loomcycle.v1.Loomcycle/Health',
            loomcycle__pb2.HealthRequest.SerializeToString,
            loomcycle__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PauseRuntime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loomcycle.v1.Loomcycle/PauseRuntime',
            loomcycle__pb2.PauseRuntimeRequest.SerializeToString,
            loomcycle__pb2.PauseRuntimeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResumeRuntime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loomcycle.v1.Loomcycle/ResumeRuntime',
            loomcycle__pb2.ResumeRuntimeRequest.SerializeToString,
            loomcycle__pb2.ResumeRuntimeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRuntimeState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loomcycle.v1.Loomcycle/GetRuntimeState',
            loomcycle__pb2.GetRuntimeStateRequest.SerializeToString,
            loomcycle__pb2.RuntimeStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateSnapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loomcycle.v1.Loomcycle/CreateSnapshot',
            loomcycle__pb2.CreateSnapshotRequest.SerializeToString,
            loomcycle__pb2.SnapshotDescriptor.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSnapshots(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loomcycle.v1.Loomcycle/ListSnapshots',
            loomcycle__pb2.ListSnapshotsRequest.SerializeToString,
            loomcycle__pb2.ListSnapshotsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSnapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loomcycle.v1.Loomcycle/GetSnapshot',
            loomcycle__pb2.GetSnapshotRequest.SerializeToString,
            loomcycle__pb2.SnapshotEnvelope.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExportSnapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loomcycle.v1.Loomcycle/ExportSnapshot',
            loomcycle__pb2.ExportSnapshotRequest.SerializeToString,
            loomcycle__pb2.ExportSnapshotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RestoreSnapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loomcycle.v1.Loomcycle/RestoreSnapshot',
            loomcycle__pb2.RestoreSnapshotRequest.SerializeToString,
            loomcycle__pb2.RestoreSnapshotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteSnapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loomcycle.v1.Loomcycle/DeleteSnapshot',
            loomcycle__pb2.DeleteSnapshotRequest.SerializeToString,
            loomcycle__pb2.DeleteSnapshotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
