# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import loomcycle_pb2 as loomcycle__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in loomcycle_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LoomcycleStub(object):
    """========================
    Service
    ========================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Run = channel.unary_stream(
                '/loomcycle.v1.Loomcycle/Run',
                request_serializer=loomcycle__pb2.RunRequest.SerializeToString,
                response_deserializer=loomcycle__pb2.Event.FromString,
                _registered_method=True)
        self.Continue = channel.unary_stream(
                '/loomcycle.v1.Loomcycle/Continue',
                request_serializer=loomcycle__pb2.ContinueRequest.SerializeToString,
                response_deserializer=loomcycle__pb2.Event.FromString,
                _registered_method=True)
        self.SpawnRunBatch = channel.unary_unary(
                '/loomcycle.v1.Loomcycle/SpawnRunBatch',
                request_serializer=loomcycle__pb2.BatchSpawnRequest.SerializeToString,
                response_deserializer=loomcycle__pb2.BatchSpawnResult.FromString,
                _registered_method=True)
        self.CompactRun = channel.unary_unary(
                '/loomcycle.v1.Loomcycle/CompactRun',
                request_serializer=loomcycle__pb2.CompactRunRequest.SerializeToString,
                response_deserializer=loomcycle__pb2.CompactRunResult.FromString,
                _registered_method=True)
        self.GetTranscript = channel.unary_unary(
                '/loomcycle.v1.Loomcycle/GetTranscript',
                request_serializer=loomcycle__pb2.GetTranscriptRequest.SerializeToString,
                response_deserializer=loomcycle__pb2.Transcript.FromString,
                _registered_method=True)
        self.GetAgent = channel.unary_unary(
                '/loomcycle.v1.Loomcycle/GetAgent',
                request_serializer=loomcycle__pb2.GetAgentRequest.SerializeToString,
                response_deserializer=loomcycle__pb2.Agent.FromString,
                _registered_method=True)
        self.CancelAgent = channel.unary_unary(
                '/loomcycle.v1.Loomcycle/CancelAgent',
                request_serializer=loomcycle__pb2.CancelAgentRequest.SerializeToString,
                response_deserializer=loomcycle__pb2.CancelAgentResponse.FromString,
                _registered_method=True)
        self.ListUserAgents = channel.unary_unary(
                '/loomcycle.v1.Loomcycle/ListUserAgents',
                request_serializer=loomcycle__pb2.ListUserAgentsRequest.SerializeToString,
                response_deserializer=loomcycle__pb2.ListUserAgentsResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/loomcycle.v1.Loomcycle/Health',
                request_serializer=loomcycle__pb2.HealthRequest.SerializeToString,
                response_deserializer=loomcycle__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.RegisterHook = channel.unary_unary(
                '/loomcycle.v1.Loomcycle/RegisterHook',
                request_serializer=loomcycle__pb2.RegisterHookRequest.SerializeToString,
                response_deserializer=loomcycle__pb2.RegisterHookResponse.FromString,
                _registered_method=True)
        self.ListHooks = channel.unary_unary(
                '/loomcycle.v1.Loomcycle/ListHooks',
                request_serializer=loomcycle__pb2.ListHooksRequest.SerializeToString,
                response_deserializer=loomcycle__pb2.ListHooksResponse.FromString,
                _registered_method=True)
        self.DeleteHook = channel.unary_unary(
                '/loomcycle.v1.Loomcycle/DeleteHook',
                request_serializer=loomcycle__pb2.DeleteHookRequest.SerializeToString,
                response_deserializer=loomcycle__pb2.DeleteHookResponse.FromString,
                _registered_method=True)
        self.PauseRuntime = channel.unary_unary(
                '/loomcycle.v1.Loomcycle/PauseRuntime',
                request_serializer=loomcycle__pb2.PauseRuntimeRequest.SerializeToString,
                response_deserializer=loomcycle__pb2.PauseRuntimeResponse.FromString,
                _registered_method=True)
        self.ResumeRuntime = channel.unary_unary(
                '/loomcycle.v1.Loomcycle/ResumeRuntime',
                request_serializer=loomcycle__pb2.ResumeRuntimeRequest.SerializeToString,
                response_deserializer=loomcycle__pb2.ResumeRuntimeResponse.FromString,
                _registered_method=True)
        self.GetRuntimeState = channel.unary_unary(
                '/loomcycle.v1.Loomcycle/GetRuntimeState',
                request_serializer=loomcycle__pb2.GetRuntimeStateRequest.SerializeToString,
                response_deserializer=loomcycle__pb2.RuntimeStateResponse.FromString,
                _registered_method=True)
        self.ResolveProbe = channel.unary_unary(
                '/loomcycle.v1.Loomcycle/ResolveProbe',
                request_serializer=loomcycle__pb2.ResolveProbeRequest.SerializeToString,
                response_deserializer=loomcycle__pb2.ResolverMatrixResponse.FromString,
                _registered_method=True)
        self.CreateSnapshot = channel.unary_unary(
                '/loomcycle.v1.Loomcycle/CreateSnapshot',
                request_serializer=loomcycle__pb2.CreateSnapshotRequest.SerializeToString,
                response_deserializer=loomcycle__pb2.SnapshotDescriptor.FromString,
                _registered_method=True)
        self.ListSnapshots = channel.unary_unary(
                '/loomcycle.v1.Loomcycle/ListSnapshots',
                request_serializer=loomcycle__pb2.ListSnapshotsRequest.SerializeToString,
                response_deserializer=loomcycle__pb2.ListSnapshotsResponse.FromString,
                _registered_method=True)
        self.GetSnapshot = channel.unary_unary(
                '/loomcycle.v1.Loomcycle/GetSnapshot',
                request_serializer=loomcycle__pb2.GetSnapshotRequest.SerializeToString,
                response_deserializer=loomcycle__pb2.SnapshotEnvelope.FromString,
                _registered_method=True)
        self.ExportSnapshot = channel.unary_unary(
                '/loomcycle.v1.Loomcycle/ExportSnapshot',
                request_serializer=loomcycle__pb2.ExportSnapshotRequest.SerializeToString,
                response_deserializer=loomcycle__pb2.ExportSnapshotResponse.FromString,
                _registered_method=True)
        self.RestoreSnapshot = channel.unary_unary(
                '/loomcycle.v1.Loomcycle/RestoreSnapshot',
                request_serializer=loomcycle__pb2.RestoreSnapshotRequest.SerializeToString,
                response_deserializer=loomcycle__pb2.RestoreSnapshotResponse.FromString,
                _registered_method=True)
        self.DeleteSnapshot = channel.unary_unary(
                '/loomcycle.v1.Loomcycle/DeleteSnapshot',
                request_serializer=loomcycle__pb2.DeleteSnapshotRequest.SerializeToString,
                response_deserializer=loomcycle__pb2.DeleteSnapshotResponse.FromString,
                _registered_method=True)
        self.AgentDef = channel.unary_unary(
                '/loomcycle.v1.Loomcycle/AgentDef',
                request_serializer=loomcycle__pb2.SubstrateRequest.SerializeToString,
                response_deserializer=loomcycle__pb2.SubstrateResponse.FromString,
                _registered_method=True)
        self.SkillDef = channel.unary_unary(
                '/loomcycle.v1.Loomcycle/SkillDef',
                request_serializer=loomcycle__pb2.SubstrateRequest.SerializeToString,
                response_deserializer=loomcycle__pb2.SubstrateResponse.FromString,
                _registered_method=True)
        self.MCPServerDef = channel.unary_unary(
                '/loomcycle.v1.Loomcycle/MCPServerDef',
                request_serializer=loomcycle__pb2.SubstrateRequest.SerializeToString,
                response_deserializer=loomcycle__pb2.SubstrateResponse.FromString,
                _registered_method=True)
        self.ScheduleDef = channel.unary_unary(
                '/loomcycle.v1.Loomcycle/ScheduleDef',
                request_serializer=loomcycle__pb2.SubstrateRequest.SerializeToString,
                response_deserializer=loomcycle__pb2.SubstrateResponse.FromString,
                _registered_method=True)
        self.A2AServerCardDef = channel.unary_unary(
                '/loomcycle.v1.Loomcycle/A2AServerCardDef',
                request_serializer=loomcycle__pb2.SubstrateRequest.SerializeToString,
                response_deserializer=loomcycle__pb2.SubstrateResponse.FromString,
                _registered_method=True)
        self.A2AAgentDef = channel.unary_unary(
                '/loomcycle.v1.Loomcycle/A2AAgentDef',
                request_serializer=loomcycle__pb2.SubstrateRequest.SerializeToString,
                response_deserializer=loomcycle__pb2.SubstrateResponse.FromString,
                _registered_method=True)
        self.WebhookDef = channel.unary_unary(
                '/loomcycle.v1.Loomcycle/WebhookDef',
                request_serializer=loomcycle__pb2.SubstrateRequest.SerializeToString,
                response_deserializer=loomcycle__pb2.SubstrateResponse.FromString,
                _registered_method=True)
        self.MemoryBackendDef = channel.unary_unary(
                '/loomcycle.v1.Loomcycle/MemoryBackendDef',
                request_serializer=loomcycle__pb2.SubstrateRequest.SerializeToString,
                response_deserializer=loomcycle__pb2.SubstrateResponse.FromString,
                _registered_method=True)
        self.OperatorTokenDef = channel.unary_unary(
                '/loomcycle.v1.Loomcycle/OperatorTokenDef',
                request_serializer=loomcycle__pb2.SubstrateRequest.SerializeToString,
                response_deserializer=loomcycle__pb2.SubstrateResponse.FromString,
                _registered_method=True)
        self.ListChannels = channel.unary_unary(
                '/loomcycle.v1.Loomcycle/ListChannels',
                request_serializer=loomcycle__pb2.ListChannelsRequest.SerializeToString,
                response_deserializer=loomcycle__pb2.ListChannelsResponse.FromString,
                _registered_method=True)
        self.StreamUserRunStates = channel.unary_stream(
                '/loomcycle.v1.Loomcycle/StreamUserRunStates',
                request_serializer=loomcycle__pb2.StreamUserRunStatesRequest.SerializeToString,
                response_deserializer=loomcycle__pb2.RunStateEvent.FromString,
                _registered_method=True)
        self.PublishChannel = channel.unary_unary(
                '/loomcycle.v1.Loomcycle/PublishChannel',
                request_serializer=loomcycle__pb2.PublishChannelRequest.SerializeToString,
                response_deserializer=loomcycle__pb2.PublishChannelResponse.FromString,
                _registered_method=True)
        self.SubscribeChannel = channel.unary_unary(
                '/loomcycle.v1.Loomcycle/SubscribeChannel',
                request_serializer=loomcycle__pb2.SubscribeChannelRequest.SerializeToString,
                response_deserializer=loomcycle__pb2.SubscribeChannelResponse.FromString,
                _registered_method=True)
        self.PeekChannel = channel.unary_unary(
                '/loomcycle.v1.Loomcycle/PeekChannel',
                request_serializer=loomcycle__pb2.PeekChannelRequest.SerializeToString,
                response_deserializer=loomcycle__pb2.PeekChannelResponse.FromString,
                _registered_method=True)
        self.AckChannel = channel.unary_unary(
                '/loomcycle.v1.Loomcycle/AckChannel',
                request_serializer=loomcycle__pb2.AckChannelRequest.SerializeToString,
                response_deserializer=loomcycle__pb2.AckChannelResponse.FromString,
                _registered_method=True)
        self.AwaitChannels = channel.unary_unary(
                '/loomcycle.v1.Loomcycle/AwaitChannels',
                request_serializer=loomcycle__pb2.AwaitChannelsRequest.SerializeToString,
                response_deserializer=loomcycle__pb2.AwaitChannelsResponse.FromString,
                _registered_method=True)
        self.BroadcastChannels = channel.unary_unary(
                '/loomcycle.v1.Loomcycle/BroadcastChannels',
                request_serializer=loomcycle__pb2.BroadcastChannelsRequest.SerializeToString,
                response_deserializer=loomcycle__pb2.BroadcastChannelsResponse.FromString,
                _registered_method=True)


class LoomcycleServicer(object):
    """========================
    Service
    ========================

    """

    def Run(self, request, context):
        """Run starts a fresh agent run and server-streams its events. One
        request → many Event responses. The stream terminates on EOF when
        the loop reaches its terminal state (done, failed, or cancelled).

        Mirrors POST /v1/runs.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Continue(self, request, context):
        """Continue extends an existing session with a new run. The session's
        prior transcript is replayed into the loop's context; the response
        stream covers only the NEW events from this continuation.

        Mirrors POST /v1/sessions/{id}/messages.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SpawnRunBatch(self, request, context):
        """SpawnRunBatch spawns N fresh runs concurrently in one call (RFC Y
        external fan-out, mode "join"), bounded by the per-user admission
        gate, returning a combined index-aligned envelope once all settle. A
        per-child failure is captured in that child's result and never fails
        the batch. mode "detach" (async run handles) is reserved for a future
        release and rejected today.

        Mirrors POST /v1/runs:batch + the spawn_runs MCP tool.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CompactRun(self, request, context):
        """CompactRun summarizes a run's conversation to free context and
        continue from the summary. A live run must be PARKED (awaiting input);
        a mid-turn run returns FailedPrecondition. Keyed by run_id.

        Mirrors POST /v1/runs/{run_id}/compact + the compact_run MCP tool.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTranscript(self, request, context):
        """GetTranscript returns the full event history for a session,
        ordered by seq. Used by adapters that re-attach to a previously
        started session (e.g. cross-tab sync).

        Mirrors GET /v1/sessions/{id}/transcript.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAgent(self, request, context):
        """GetAgent returns one agent's current status + usage stats. Used
        by adapters polling for completion when the SSE/gRPC stream was
        interrupted (browser tab closed, network blip).

        Mirrors GET /v1/agents/{agent_id}.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelAgent(self, request, context):
        """CancelAgent sets the agent's terminal status to "cancelled" and
        cascades the cancellation to every child via parent_agent_id.

        Mirrors POST /v1/agents/{agent_id}/cancel.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListUserAgents(self, request, context):
        """ListUserAgents enumerates a user's recent agent runs, optionally
        filtered by status.

        Mirrors GET /v1/users/{user_id}/agents.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Health is the liveness probe. Returns build identifier + uptime.

        Mirrors GET /healthz (which is unauthenticated on the HTTP side;
        the gRPC equivalent stays unauthenticated for parity).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterHook(self, request, context):
        """RegisterHook registers a pre- or post-tool webhook. The
        callback_url must be an http:// or https:// endpoint the consumer
        runs. Returns the loomcycle-assigned id. Re-registering the same
        (owner, name) replaces the prior entry in-place (idempotent on
        app restart).

        Mirrors POST /v1/hooks.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListHooks(self, request, context):
        """ListHooks returns every currently-registered hook. Useful for
        debug; no pagination — the registry is intentionally small
        (operator-curated set).

        Mirrors GET /v1/hooks.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteHook(self, request, context):
        """DeleteHook removes a registered hook by id. Returns
        codes.NotFound when no hook has that id.

        Mirrors DELETE /v1/hooks/{id}.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PauseRuntime(self, request, context):
        """----- v0.8.17 Pause / Resume / Snapshot (real impls in v0.8.18) -----

        Runtime-wide quiesce + cross-version-portable JSON snapshot. Wire
        shapes mirror the connector.Connector method signatures. Typed
        errors from internal/connector/errors.go map to gRPC codes:
        ErrPauseNotConfigured     → Unavailable (503-equivalent)
        ErrAlreadyPausing         → FailedPrecondition (409-equivalent)
        ErrNotPaused              → FailedPrecondition (409-equivalent)
        ErrSnapshotNotFound       → NotFound (404-equivalent)
        ErrSnapshotTooLarge       → ResourceExhausted (413-equivalent)
        ErrSnapshotVersionTooNew  → FailedPrecondition (422-equivalent)
        ErrSnapshotVersionUnknown → FailedPrecondition (422-equivalent)

        PauseRuntime quiesces the runtime. Idempotent tools cancel
        immediately; non-idempotent + external tools get a grace window
        (default 30 s; max 5 min) then force-cancel. Returns 409-equivalent
        when the runtime is already pausing or paused.

        Mirrors POST /v1/_pause.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResumeRuntime(self, request, context):
        """ResumeRuntime releases the quiesce. Paused runs re-enter their
        loops. Returns 409-equivalent when the runtime is not paused.

        Mirrors POST /v1/_resume.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRuntimeState(self, request, context):
        """GetRuntimeState returns the current quiesce state for dashboards.

        Mirrors GET /v1/_state.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResolveProbe(self, request, context):
        """ResolveProbe triggers an immediate, synchronous re-probe of every
        configured provider and returns the refreshed availability matrix
        — the operator escape hatch when a transient outage stalls every
        provider. Unavailable when no resolver / no probe loop is wired.

        Mirrors POST /v1/_resolve/probe.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateSnapshot(self, request, context):
        """CreateSnapshot captures running-state into a per-section-semver
        JSON envelope (agent_defs, agent_def_active, memory, channels,
        evaluations, paused_runs, optional interaction_history). Returns
        413-equivalent when the serialised envelope exceeds the configured
        cap (LOOMCYCLE_SNAPSHOT_MAX_BYTES; default 512 MiB).

        Mirrors POST /v1/_snapshots.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSnapshots(self, request, context):
        """ListSnapshots returns metadata for the most-recent snapshots
        (capped at 200). The JSON envelope itself is not included; use
        GetSnapshot / ExportSnapshot to fetch.

        Mirrors GET /v1/_snapshots.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSnapshot(self, request, context):
        """GetSnapshot returns the full envelope including JSON content.
        Distinct from ExportSnapshot, which is operator-facing "where did
        this land on the host" semantics.

        Mirrors GET /v1/_snapshots/{id}.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExportSnapshot(self, request, context):
        """ExportSnapshot returns canonical envelope bytes (raw_json) for a
        snapshot id. Transports that stream large exports use raw_json
        directly; file_path / checksum stay empty unless materialised.

        Mirrors GET /v1/_snapshots/{id}/export.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RestoreSnapshot(self, request, context):
        """RestoreSnapshot restores from a same-instance snapshot_id OR
        cross-instance raw_json. Idempotent: ON CONFLICT DO NOTHING per
        row. Counters in the response reflect rows actually written.
        Returns 422-equivalent on snapshot version newer than reader
        supports.

        Mirrors POST /v1/_snapshots/{id}/restore.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteSnapshot(self, request, context):
        """DeleteSnapshot removes a snapshot. Idempotent — succeeds whether
        or not the row existed.

        Mirrors DELETE /v1/_snapshots/{id}.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AgentDef(self, request, context):
        """----- v0.8.22 substrate admin RPCs -----

        Two op-discriminated RPCs expose the AgentDef + SkillDef
        substrate tools to gRPC callers (and through the gRPC adapter
        path to Python clients). Same connector dispatch as the MCP
        meta-tools and the HTTP /v1/_agentdef + /v1/_skilldef
        endpoints — different transport, identical semantics.

        Request body is the substrate tool's input JSON (op + name +
        def_id + overlay + ...); response carries the tool's output
        JSON + an is_error flag. Errors that aren't tool refusals
        (transport, auth, malformed body) come back as gRPC status
        codes per the existing convention.

        AgentDef dispatches to the in-process AgentDef tool. Mirrors
        POST /v1/_agentdef.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SkillDef(self, request, context):
        """SkillDef dispatches to the in-process SkillDef tool. Mirrors
        POST /v1/_skilldef.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MCPServerDef(self, request, context):
        """MCPServerDef dispatches to the v0.9.x dynamic MCP server
        registration substrate. Mirrors POST /v1/_mcpserverdef.
        Operator-admin-only — same SubstrateRequest body shape as
        AgentDef + SkillDef (op-discriminated input_json + is_error
        tool refusals in the response).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ScheduleDef(self, request, context):
        """ScheduleDef dispatches to the v1.x RFC E scheduled-runs
        substrate. Mirrors POST /v1/_scheduledef. Operator-admin-only.
        Same SubstrateRequest body shape — op-discriminated input_json
        (create / fork / get / list / retire) + is_error tool refusals
        in the response.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def A2AServerCardDef(self, request, context):
        """A2AServerCardDef dispatches to the v1.x RFC G A2A-server-card
        substrate. Mirrors POST /v1/_a2aservercarddef. Operator-admin-only.
        Same SubstrateRequest body shape — op-discriminated input_json
        (create / fork / get / list / retire) + is_error tool refusals
        in the response.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def A2AAgentDef(self, request, context):
        """A2AAgentDef dispatches to the v1.x RFC G A2A-agent substrate.
        Mirrors POST /v1/_a2aagentdef. Operator-admin-only. Same
        SubstrateRequest body shape — op-discriminated input_json
        (create / fork / get / list / retire) + is_error tool refusals
        in the response.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WebhookDef(self, request, context):
        """WebhookDef dispatches to the v1.x RFC H inbound-webhook substrate.
        Mirrors POST /v1/_webhookdef. Operator-admin-only. Same
        SubstrateRequest body shape — op-discriminated input_json
        (create / fork / get / list / retire) + is_error tool refusals
        in the response. (RFC H WH-3 / mirrors A2AAgentDef.)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MemoryBackendDef(self, request, context):
        """MemoryBackendDef dispatches to the RFC I MR-3a memory-backend
        substrate. Mirrors POST /v1/_memorybackenddef. Operator-admin-only.
        Same SubstrateRequest body shape — op-discriminated input_json
        (create / fork / get / list / retire) + is_error tool refusals
        in the response. (RFC I MR-3a / mirrors WebhookDef.)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OperatorTokenDef(self, request, context):
        """OperatorTokenDef dispatches to the RFC L OSS multi-tenant
        authorization substrate (auth-token minting/rotation/retirement).
        Mirrors POST /v1/_operatortokendef. Operator-admin-only. Same
        SubstrateRequest body shape — op-discriminated input_json
        (create / rotate / retire / get / list).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListChannels(self, request, context):
        """----- v0.9.x n8n RFC Phase 0 -----

        ListChannels mirrors GET /v1/_channels — operator-declared
        channels joined with runtime stats.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamUserRunStates(self, request, context):
        """StreamUserRunStates mirrors GET /v1/users/{user_id}/agents/stream.
        Server-streams one RunStateEvent per matching state transition
        until ctx cancels or the client closes the stream.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PublishChannel(self, request, context):
        """----- v0.9.x Channel CRUD (admin + per-user) -----

        Mirrors the four HTTP routes:
        PublishChannel   → POST /v1/_channels/{name}/publish (and the
        /v1/users/{user_id}/channels/... variant)
        SubscribeChannel → POST /v1/_channels/{name}/subscribe (single-
        round-trip long-poll; not streaming)
        PeekChannel      → GET  /v1/_channels/{name}/peek (non-destructive)
        AckChannel       → POST /v1/_channels/{name}/ack

        Scope + scope_id select the cursor namespace: scope="global" with
        empty scope_id addresses the admin surface; scope="user" with a
        non-empty scope_id addresses a per-end-user channel.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeChannel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PeekChannel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AckChannel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AwaitChannels(self, request, context):
        """RFC S client twins (mirror POST /v1/_channels/_await and
        /v1/_channels/_broadcast). AwaitChannels fans IN across a set of
        channels (any/all/at_least N, or a timeout — a timeout is
        satisfied=false / timed_out=true, NOT an error); BroadcastChannels
        fans OUT one payload to a set of channels (atomic at the declare
        pre-flight). Scope + scope_id apply to every channel in the set.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BroadcastChannels(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LoomcycleServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Run': grpc.unary_stream_rpc_method_handler(
                    servicer.Run,
                    request_deserializer=loomcycle__pb2.RunRequest.FromString,
                    response_serializer=loomcycle__pb2.Event.SerializeToString,
            ),
            'Continue': grpc.unary_stream_rpc_method_handler(
                    servicer.Continue,
                    request_deserializer=loomcycle__pb2.ContinueRequest.FromString,
                    response_serializer=loomcycle__pb2.Event.SerializeToString,
            ),
            'SpawnRunBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.SpawnRunBatch,
                    request_deserializer=loomcycle__pb2.BatchSpawnRequest.FromString,
                    response_serializer=loomcycle__pb2.BatchSpawnResult.SerializeToString,
            ),
            'CompactRun': grpc.unary_unary_rpc_method_handler(
                    servicer.CompactRun,
                    request_deserializer=loomcycle__pb2.CompactRunRequest.FromString,
                    response_serializer=loomcycle__pb2.CompactRunResult.SerializeToString,
            ),
            'GetTranscript': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTranscript,
                    request_deserializer=loomcycle__pb2.GetTranscriptRequest.FromString,
                    response_serializer=loomcycle__pb2.Transcript.SerializeToString,
            ),
            'GetAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAgent,
                    request_deserializer=loomcycle__pb2.GetAgentRequest.FromString,
                    response_serializer=loomcycle__pb2.Agent.SerializeToString,
            ),
            'CancelAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelAgent,
                    request_deserializer=loomcycle__pb2.CancelAgentRequest.FromString,
                    response_serializer=loomcycle__pb2.CancelAgentResponse.SerializeToString,
            ),
            'ListUserAgents': grpc.unary_unary_rpc_method_handler(
                    servicer.ListUserAgents,
                    request_deserializer=loomcycle__pb2.ListUserAgentsRequest.FromString,
                    response_serializer=loomcycle__pb2.ListUserAgentsResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=loomcycle__pb2.HealthRequest.FromString,
                    response_serializer=loomcycle__pb2.HealthResponse.SerializeToString,
            ),
            'RegisterHook': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterHook,
                    request_deserializer=loomcycle__pb2.RegisterHookRequest.FromString,
                    response_serializer=loomcycle__pb2.RegisterHookResponse.SerializeToString,
            ),
            'ListHooks': grpc.unary_unary_rpc_method_handler(
                    servicer.ListHooks,
                    request_deserializer=loomcycle__pb2.ListHooksRequest.FromString,
                    response_serializer=loomcycle__pb2.ListHooksResponse.SerializeToString,
            ),
            'DeleteHook': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteHook,
                    request_deserializer=loomcycle__pb2.DeleteHookRequest.FromString,
                    response_serializer=loomcycle__pb2.DeleteHookResponse.SerializeToString,
            ),
            'PauseRuntime': grpc.unary_unary_rpc_method_handler(
                    servicer.PauseRuntime,
                    request_deserializer=loomcycle__pb2.PauseRuntimeRequest.FromString,
                    response_serializer=loomcycle__pb2.PauseRuntimeResponse.SerializeToString,
            ),
            'ResumeRuntime': grpc.unary_unary_rpc_method_handler(
                    servicer.ResumeRuntime,
                    request_deserializer=loomcycle__pb2.ResumeRuntimeRequest.FromString,
                    response_serializer=loomcycle__pb2.ResumeRuntimeResponse.SerializeToString,
            ),
            'GetRuntimeState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRuntimeState,
                    request_deserializer=loomcycle__pb2.GetRuntimeStateRequest.FromString,
                    response_serializer=loomcycle__pb2.RuntimeStateResponse.SerializeToString,
            ),
            'ResolveProbe': grpc.unary_unary_rpc_method_handler(
                    servicer.ResolveProbe,
                    request_deserializer=loomcycle__pb2.ResolveProbeRequest.FromString,
                    response_serializer=loomcycle__pb2.ResolverMatrixResponse.SerializeToString,
            ),
            'CreateSnapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSnapshot,
                    request_deserializer=loomcycle__pb2.CreateSnapshotRequest.FromString,
                    response_serializer=loomcycle__pb2.SnapshotDescriptor.SerializeToString,
            ),
            'ListSnapshots': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSnapshots,
                    request_deserializer=loomcycle__pb2.ListSnapshotsRequest.FromString,
                    response_serializer=loomcycle__pb2.ListSnapshotsResponse.SerializeToString,
            ),
            'GetSnapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSnapshot,
                    request_deserializer=loomcycle__pb2.GetSnapshotRequest.FromString,
                    response_serializer=loomcycle__pb2.SnapshotEnvelope.SerializeToString,
            ),
            'ExportSnapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.ExportSnapshot,
                    request_deserializer=loomcycle__pb2.ExportSnapshotRequest.FromString,
                    response_serializer=loomcycle__pb2.ExportSnapshotResponse.SerializeToString,
            ),
            'RestoreSnapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.RestoreSnapshot,
                    request_deserializer=loomcycle__pb2.RestoreSnapshotRequest.FromString,
                    response_serializer=loomcycle__pb2.RestoreSnapshotResponse.SerializeToString,
            ),
            'DeleteSnapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteSnapshot,
                    request_deserializer=loomcycle__pb2.DeleteSnapshotRequest.FromString,
                    response_serializer=loomcycle__pb2.DeleteSnapshotResponse.SerializeToString,
            ),
            'AgentDef': grpc.unary_unary_rpc_method_handler(
                    servicer.AgentDef,
                    request_deserializer=loomcycle__pb2.SubstrateRequest.FromString,
                    response_serializer=loomcycle__pb2.SubstrateResponse.SerializeToString,
            ),
            'SkillDef': grpc.unary_unary_rpc_method_handler(
                    servicer.SkillDef,
                    request_deserializer=loomcycle__pb2.SubstrateRequest.FromString,
                    response_serializer=loomcycle__pb2.SubstrateResponse.SerializeToString,
            ),
            'MCPServerDef': grpc.unary_unary_rpc_method_handler(
                    servicer.MCPServerDef,
                    request_deserializer=loomcycle__pb2.SubstrateRequest.FromString,
                    response_serializer=loomcycle__pb2.SubstrateResponse.SerializeToString,
            ),
            'ScheduleDef': grpc.unary_unary_rpc_method_handler(
                    servicer.ScheduleDef,
                    request_deserializer=loomcycle__pb2.SubstrateRequest.FromString,
                    response_serializer=loomcycle__pb2.SubstrateResponse.SerializeToString,
            ),
            'A2AServerCardDef': grpc.unary_unary_rpc_method_handler(
                    servicer.A2AServerCardDef,
                    request_deserializer=loomcycle__pb2.SubstrateRequest.FromString,
                    response_serializer=loomcycle__pb2.SubstrateResponse.SerializeToString,
            ),
            'A2AAgentDef': grpc.unary_unary_rpc_method_handler(
                    servicer.A2AAgentDef,
                    request_deserializer=loomcycle__pb2.SubstrateRequest.FromString,
                    response_serializer=loomcycle__pb2.SubstrateResponse.SerializeToString,
            ),
            'WebhookDef': grpc.unary_unary_rpc_method_handler(
                    servicer.WebhookDef,
                    request_deserializer=loomcycle__pb2.SubstrateRequest.FromString,
                    response_serializer=loomcycle__pb2.SubstrateResponse.SerializeToString,
            ),
            'MemoryBackendDef': grpc.unary_unary_rpc_method_handler(
                    servicer.MemoryBackendDef,
                    request_deserializer=loomcycle__pb2.SubstrateRequest.FromString,
                    response_serializer=loomcycle__pb2.SubstrateResponse.SerializeToString,
            ),
            'OperatorTokenDef': grpc.unary_unary_rpc_method_handler(
                    servicer.OperatorTokenDef,
                    request_deserializer=loomcycle__pb2.SubstrateRequest.FromString,
                    response_serializer=loomcycle__pb2.SubstrateResponse.SerializeToString,
            ),
            'ListChannels': grpc.unary_unary_rpc_method_handler(
                    servicer.ListChannels,
                    request_deserializer=loomcycle__pb2.ListChannelsRequest.FromString,
                    response_serializer=loomcycle__pb2.ListChannelsResponse.SerializeToString,
            ),
            'StreamUserRunStates': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamUserRunStates,
                    request_deserializer=loomcycle__pb2.StreamUserRunStatesRequest.FromString,
                    response_serializer=loomcycle__pb2.RunStateEvent.SerializeToString,
            ),
            'PublishChannel': grpc.unary_unary_rpc_method_handler(
                    servicer.PublishChannel,
                    request_deserializer=loomcycle__pb2.PublishChannelRequest.FromString,
                    response_serializer=loomcycle__pb2.PublishChannelResponse.SerializeToString,
            ),
            'SubscribeChannel': grpc.unary_unary_rpc_method_handler(
                    servicer.SubscribeChannel,
                    request_deserializer=loomcycle__pb2.SubscribeChannelRequest.FromString,
                    response_serializer=loomcycle__pb2.SubscribeChannelResponse.SerializeToString,
            ),
            'PeekChannel': grpc.unary_unary_rpc_method_handler(
                    servicer.PeekChannel,
                    request_deserializer=loomcycle__pb2.PeekChannelRequest.FromString,
                    response_serializer=loomcycle__pb2.PeekChannelResponse.SerializeToString,
            ),
            'AckChannel': grpc.unary_unary_rpc_method_handler(
                    servicer.AckChannel,
                    request_deserializer=loomcycle__pb2.AckChannelRequest.FromString,
                    response_serializer=loomcycle__pb2.AckChannelResponse.SerializeToString,
            ),
            'AwaitChannels': grpc.unary_unary_rpc_method_handler(
                    servicer.AwaitChannels,
                    request_deserializer=loomcycle__pb2.AwaitChannelsRequest.FromString,
                    response_serializer=loomcycle__pb2.AwaitChannelsResponse.SerializeToString,
            ),
            'BroadcastChannels': grpc.unary_unary_rpc_method_handler(
                    servicer.BroadcastChannels,
                    request_deserializer=loomcycle__pb2.BroadcastChannelsRequest.FromString,
                    response_serializer=loomcycle__pb2.BroadcastChannelsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'loomcycle.v1.Loomcycle', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('loomcycle.v1.Loomcycle', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Loomcycle(object):
    """========================
    Service
    ========================

    """

    @staticmethod
    def Run(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/loomcycle.v1.Loomcycle/Run',
            loomcycle__pb2.RunRequest.SerializeToString,
            loomcycle__pb2.Event.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Continue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/loomcycle.v1.Loomcycle/Continue',
            loomcycle__pb2.ContinueRequest.SerializeToString,
            loomcycle__pb2.Event.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SpawnRunBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loomcycle.v1.Loomcycle/SpawnRunBatch',
            loomcycle__pb2.BatchSpawnRequest.SerializeToString,
            loomcycle__pb2.BatchSpawnResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CompactRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loomcycle.v1.Loomcycle/CompactRun',
            loomcycle__pb2.CompactRunRequest.SerializeToString,
            loomcycle__pb2.CompactRunResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTranscript(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loomcycle.v1.Loomcycle/GetTranscript',
            loomcycle__pb2.GetTranscriptRequest.SerializeToString,
            loomcycle__pb2.Transcript.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loomcycle.v1.Loomcycle/GetAgent',
            loomcycle__pb2.GetAgentRequest.SerializeToString,
            loomcycle__pb2.Agent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loomcycle.v1.Loomcycle/CancelAgent',
            loomcycle__pb2.CancelAgentRequest.SerializeToString,
            loomcycle__pb2.CancelAgentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListUserAgents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loomcycle.v1.Loomcycle/ListUserAgents',
            loomcycle__pb2.ListUserAgentsRequest.SerializeToString,
            loomcycle__pb2.ListUserAgentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loomcycle.v1.Loomcycle/Health',
            loomcycle__pb2.HealthRequest.SerializeToString,
            loomcycle__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterHook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loomcycle.v1.Loomcycle/RegisterHook',
            loomcycle__pb2.RegisterHookRequest.SerializeToString,
            loomcycle__pb2.RegisterHookResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListHooks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loomcycle.v1.Loomcycle/ListHooks',
            loomcycle__pb2.ListHooksRequest.SerializeToString,
            loomcycle__pb2.ListHooksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteHook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loomcycle.v1.Loomcycle/DeleteHook',
            loomcycle__pb2.DeleteHookRequest.SerializeToString,
            loomcycle__pb2.DeleteHookResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PauseRuntime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loomcycle.v1.Loomcycle/PauseRuntime',
            loomcycle__pb2.PauseRuntimeRequest.SerializeToString,
            loomcycle__pb2.PauseRuntimeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResumeRuntime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loomcycle.v1.Loomcycle/ResumeRuntime',
            loomcycle__pb2.ResumeRuntimeRequest.SerializeToString,
            loomcycle__pb2.ResumeRuntimeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRuntimeState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loomcycle.v1.Loomcycle/GetRuntimeState',
            loomcycle__pb2.GetRuntimeStateRequest.SerializeToString,
            loomcycle__pb2.RuntimeStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResolveProbe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loomcycle.v1.Loomcycle/ResolveProbe',
            loomcycle__pb2.ResolveProbeRequest.SerializeToString,
            loomcycle__pb2.ResolverMatrixResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateSnapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loomcycle.v1.Loomcycle/CreateSnapshot',
            loomcycle__pb2.CreateSnapshotRequest.SerializeToString,
            loomcycle__pb2.SnapshotDescriptor.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSnapshots(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loomcycle.v1.Loomcycle/ListSnapshots',
            loomcycle__pb2.ListSnapshotsRequest.SerializeToString,
            loomcycle__pb2.ListSnapshotsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSnapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loomcycle.v1.Loomcycle/GetSnapshot',
            loomcycle__pb2.GetSnapshotRequest.SerializeToString,
            loomcycle__pb2.SnapshotEnvelope.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExportSnapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loomcycle.v1.Loomcycle/ExportSnapshot',
            loomcycle__pb2.ExportSnapshotRequest.SerializeToString,
            loomcycle__pb2.ExportSnapshotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RestoreSnapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loomcycle.v1.Loomcycle/RestoreSnapshot',
            loomcycle__pb2.RestoreSnapshotRequest.SerializeToString,
            loomcycle__pb2.RestoreSnapshotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteSnapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loomcycle.v1.Loomcycle/DeleteSnapshot',
            loomcycle__pb2.DeleteSnapshotRequest.SerializeToString,
            loomcycle__pb2.DeleteSnapshotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AgentDef(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loomcycle.v1.Loomcycle/AgentDef',
            loomcycle__pb2.SubstrateRequest.SerializeToString,
            loomcycle__pb2.SubstrateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SkillDef(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loomcycle.v1.Loomcycle/SkillDef',
            loomcycle__pb2.SubstrateRequest.SerializeToString,
            loomcycle__pb2.SubstrateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MCPServerDef(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loomcycle.v1.Loomcycle/MCPServerDef',
            loomcycle__pb2.SubstrateRequest.SerializeToString,
            loomcycle__pb2.SubstrateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ScheduleDef(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loomcycle.v1.Loomcycle/ScheduleDef',
            loomcycle__pb2.SubstrateRequest.SerializeToString,
            loomcycle__pb2.SubstrateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def A2AServerCardDef(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loomcycle.v1.Loomcycle/A2AServerCardDef',
            loomcycle__pb2.SubstrateRequest.SerializeToString,
            loomcycle__pb2.SubstrateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def A2AAgentDef(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loomcycle.v1.Loomcycle/A2AAgentDef',
            loomcycle__pb2.SubstrateRequest.SerializeToString,
            loomcycle__pb2.SubstrateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WebhookDef(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loomcycle.v1.Loomcycle/WebhookDef',
            loomcycle__pb2.SubstrateRequest.SerializeToString,
            loomcycle__pb2.SubstrateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MemoryBackendDef(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loomcycle.v1.Loomcycle/MemoryBackendDef',
            loomcycle__pb2.SubstrateRequest.SerializeToString,
            loomcycle__pb2.SubstrateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OperatorTokenDef(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loomcycle.v1.Loomcycle/OperatorTokenDef',
            loomcycle__pb2.SubstrateRequest.SerializeToString,
            loomcycle__pb2.SubstrateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListChannels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loomcycle.v1.Loomcycle/ListChannels',
            loomcycle__pb2.ListChannelsRequest.SerializeToString,
            loomcycle__pb2.ListChannelsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamUserRunStates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/loomcycle.v1.Loomcycle/StreamUserRunStates',
            loomcycle__pb2.StreamUserRunStatesRequest.SerializeToString,
            loomcycle__pb2.RunStateEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PublishChannel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loomcycle.v1.Loomcycle/PublishChannel',
            loomcycle__pb2.PublishChannelRequest.SerializeToString,
            loomcycle__pb2.PublishChannelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeChannel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loomcycle.v1.Loomcycle/SubscribeChannel',
            loomcycle__pb2.SubscribeChannelRequest.SerializeToString,
            loomcycle__pb2.SubscribeChannelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PeekChannel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loomcycle.v1.Loomcycle/PeekChannel',
            loomcycle__pb2.PeekChannelRequest.SerializeToString,
            loomcycle__pb2.PeekChannelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AckChannel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loomcycle.v1.Loomcycle/AckChannel',
            loomcycle__pb2.AckChannelRequest.SerializeToString,
            loomcycle__pb2.AckChannelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AwaitChannels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loomcycle.v1.Loomcycle/AwaitChannels',
            loomcycle__pb2.AwaitChannelsRequest.SerializeToString,
            loomcycle__pb2.AwaitChannelsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BroadcastChannels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loomcycle.v1.Loomcycle/BroadcastChannels',
            loomcycle__pb2.BroadcastChannelsRequest.SerializeToString,
            loomcycle__pb2.BroadcastChannelsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
