# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import loomcycle_pb2 as loomcycle__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in loomcycle_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LoomcycleStub(object):
    """========================
    Service
    ========================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Run = channel.unary_stream(
                '/loomcycle.v1.Loomcycle/Run',
                request_serializer=loomcycle__pb2.RunRequest.SerializeToString,
                response_deserializer=loomcycle__pb2.Event.FromString,
                _registered_method=True)
        self.Continue = channel.unary_stream(
                '/loomcycle.v1.Loomcycle/Continue',
                request_serializer=loomcycle__pb2.ContinueRequest.SerializeToString,
                response_deserializer=loomcycle__pb2.Event.FromString,
                _registered_method=True)
        self.GetTranscript = channel.unary_unary(
                '/loomcycle.v1.Loomcycle/GetTranscript',
                request_serializer=loomcycle__pb2.GetTranscriptRequest.SerializeToString,
                response_deserializer=loomcycle__pb2.Transcript.FromString,
                _registered_method=True)
        self.GetAgent = channel.unary_unary(
                '/loomcycle.v1.Loomcycle/GetAgent',
                request_serializer=loomcycle__pb2.GetAgentRequest.SerializeToString,
                response_deserializer=loomcycle__pb2.Agent.FromString,
                _registered_method=True)
        self.CancelAgent = channel.unary_unary(
                '/loomcycle.v1.Loomcycle/CancelAgent',
                request_serializer=loomcycle__pb2.CancelAgentRequest.SerializeToString,
                response_deserializer=loomcycle__pb2.CancelAgentResponse.FromString,
                _registered_method=True)
        self.ListUserAgents = channel.unary_unary(
                '/loomcycle.v1.Loomcycle/ListUserAgents',
                request_serializer=loomcycle__pb2.ListUserAgentsRequest.SerializeToString,
                response_deserializer=loomcycle__pb2.ListUserAgentsResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/loomcycle.v1.Loomcycle/Health',
                request_serializer=loomcycle__pb2.HealthRequest.SerializeToString,
                response_deserializer=loomcycle__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.RegisterHook = channel.unary_unary(
                '/loomcycle.v1.Loomcycle/RegisterHook',
                request_serializer=loomcycle__pb2.RegisterHookRequest.SerializeToString,
                response_deserializer=loomcycle__pb2.RegisterHookResponse.FromString,
                _registered_method=True)
        self.ListHooks = channel.unary_unary(
                '/loomcycle.v1.Loomcycle/ListHooks',
                request_serializer=loomcycle__pb2.ListHooksRequest.SerializeToString,
                response_deserializer=loomcycle__pb2.ListHooksResponse.FromString,
                _registered_method=True)
        self.DeleteHook = channel.unary_unary(
                '/loomcycle.v1.Loomcycle/DeleteHook',
                request_serializer=loomcycle__pb2.DeleteHookRequest.SerializeToString,
                response_deserializer=loomcycle__pb2.DeleteHookResponse.FromString,
                _registered_method=True)


class LoomcycleServicer(object):
    """========================
    Service
    ========================

    """

    def Run(self, request, context):
        """Run starts a fresh agent run and server-streams its events. One
        request → many Event responses. The stream terminates on EOF when
        the loop reaches its terminal state (done, failed, or cancelled).

        Mirrors POST /v1/runs.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Continue(self, request, context):
        """Continue extends an existing session with a new run. The session's
        prior transcript is replayed into the loop's context; the response
        stream covers only the NEW events from this continuation.

        Mirrors POST /v1/sessions/{id}/messages.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTranscript(self, request, context):
        """GetTranscript returns the full event history for a session,
        ordered by seq. Used by adapters that re-attach to a previously
        started session (e.g. cross-tab sync).

        Mirrors GET /v1/sessions/{id}/transcript.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAgent(self, request, context):
        """GetAgent returns one agent's current status + usage stats. Used
        by adapters polling for completion when the SSE/gRPC stream was
        interrupted (browser tab closed, network blip).

        Mirrors GET /v1/agents/{agent_id}.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelAgent(self, request, context):
        """CancelAgent sets the agent's terminal status to "cancelled" and
        cascades the cancellation to every child via parent_agent_id.

        Mirrors POST /v1/agents/{agent_id}/cancel.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListUserAgents(self, request, context):
        """ListUserAgents enumerates a user's recent agent runs, optionally
        filtered by status.

        Mirrors GET /v1/users/{user_id}/agents.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Health is the liveness probe. Returns build identifier + uptime.

        Mirrors GET /healthz (which is unauthenticated on the HTTP side;
        the gRPC equivalent stays unauthenticated for parity).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterHook(self, request, context):
        """RegisterHook registers a pre- or post-tool webhook. The
        callback_url must be an http:// or https:// endpoint the consumer
        runs. Returns the loomcycle-assigned id. Re-registering the same
        (owner, name) replaces the prior entry in-place (idempotent on
        app restart).

        Mirrors POST /v1/hooks.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListHooks(self, request, context):
        """ListHooks returns every currently-registered hook. Useful for
        debug; no pagination — the registry is intentionally small
        (operator-curated set).

        Mirrors GET /v1/hooks.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteHook(self, request, context):
        """DeleteHook removes a registered hook by id. Returns
        codes.NotFound when no hook has that id.

        Mirrors DELETE /v1/hooks/{id}.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LoomcycleServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Run': grpc.unary_stream_rpc_method_handler(
                    servicer.Run,
                    request_deserializer=loomcycle__pb2.RunRequest.FromString,
                    response_serializer=loomcycle__pb2.Event.SerializeToString,
            ),
            'Continue': grpc.unary_stream_rpc_method_handler(
                    servicer.Continue,
                    request_deserializer=loomcycle__pb2.ContinueRequest.FromString,
                    response_serializer=loomcycle__pb2.Event.SerializeToString,
            ),
            'GetTranscript': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTranscript,
                    request_deserializer=loomcycle__pb2.GetTranscriptRequest.FromString,
                    response_serializer=loomcycle__pb2.Transcript.SerializeToString,
            ),
            'GetAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAgent,
                    request_deserializer=loomcycle__pb2.GetAgentRequest.FromString,
                    response_serializer=loomcycle__pb2.Agent.SerializeToString,
            ),
            'CancelAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelAgent,
                    request_deserializer=loomcycle__pb2.CancelAgentRequest.FromString,
                    response_serializer=loomcycle__pb2.CancelAgentResponse.SerializeToString,
            ),
            'ListUserAgents': grpc.unary_unary_rpc_method_handler(
                    servicer.ListUserAgents,
                    request_deserializer=loomcycle__pb2.ListUserAgentsRequest.FromString,
                    response_serializer=loomcycle__pb2.ListUserAgentsResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=loomcycle__pb2.HealthRequest.FromString,
                    response_serializer=loomcycle__pb2.HealthResponse.SerializeToString,
            ),
            'RegisterHook': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterHook,
                    request_deserializer=loomcycle__pb2.RegisterHookRequest.FromString,
                    response_serializer=loomcycle__pb2.RegisterHookResponse.SerializeToString,
            ),
            'ListHooks': grpc.unary_unary_rpc_method_handler(
                    servicer.ListHooks,
                    request_deserializer=loomcycle__pb2.ListHooksRequest.FromString,
                    response_serializer=loomcycle__pb2.ListHooksResponse.SerializeToString,
            ),
            'DeleteHook': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteHook,
                    request_deserializer=loomcycle__pb2.DeleteHookRequest.FromString,
                    response_serializer=loomcycle__pb2.DeleteHookResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'loomcycle.v1.Loomcycle', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('loomcycle.v1.Loomcycle', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Loomcycle(object):
    """========================
    Service
    ========================

    """

    @staticmethod
    def Run(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/loomcycle.v1.Loomcycle/Run',
            loomcycle__pb2.RunRequest.SerializeToString,
            loomcycle__pb2.Event.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Continue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/loomcycle.v1.Loomcycle/Continue',
            loomcycle__pb2.ContinueRequest.SerializeToString,
            loomcycle__pb2.Event.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTranscript(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loomcycle.v1.Loomcycle/GetTranscript',
            loomcycle__pb2.GetTranscriptRequest.SerializeToString,
            loomcycle__pb2.Transcript.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loomcycle.v1.Loomcycle/GetAgent',
            loomcycle__pb2.GetAgentRequest.SerializeToString,
            loomcycle__pb2.Agent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loomcycle.v1.Loomcycle/CancelAgent',
            loomcycle__pb2.CancelAgentRequest.SerializeToString,
            loomcycle__pb2.CancelAgentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListUserAgents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loomcycle.v1.Loomcycle/ListUserAgents',
            loomcycle__pb2.ListUserAgentsRequest.SerializeToString,
            loomcycle__pb2.ListUserAgentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loomcycle.v1.Loomcycle/Health',
            loomcycle__pb2.HealthRequest.SerializeToString,
            loomcycle__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterHook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loomcycle.v1.Loomcycle/RegisterHook',
            loomcycle__pb2.RegisterHookRequest.SerializeToString,
            loomcycle__pb2.RegisterHookResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListHooks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loomcycle.v1.Loomcycle/ListHooks',
            loomcycle__pb2.ListHooksRequest.SerializeToString,
            loomcycle__pb2.ListHooksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteHook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loomcycle.v1.Loomcycle/DeleteHook',
            loomcycle__pb2.DeleteHookRequest.SerializeToString,
            loomcycle__pb2.DeleteHookResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
