package builtin

// document_image.go — what text to embed for an image chunk (RFC BU phase 4).
//
// Pixels are not text, so unlike mermaid an image genuinely needs a model. That
// makes it the one chunk type whose searchable text may not exist at write time,
// and the whole design of this file follows from refusing to let that block a write.
//
// TWO INDEPENDENT SOURCES, composed:
//
//   - the CAPTION — the author's own alt text. Human language, needs no model, and
//     available the instant the chunk is written.
//   - the DESCRIPTION — generated by a vision model, persisted next to the asset.
//
// The caption is why an image is searchable immediately rather than only after a
// describe pass has run. Waiting for the model would mean that every image is
// unsearchable for as long as the operator has not swept, and on a deployment with
// no vision model reachable, forever — for text the author already supplied.
//
// WHY THE DESCRIPTION IS PERSISTED rather than regenerated per embed:
//
//   - it is model output, so regenerating yields DIFFERENT text. An index that
//     silently re-ranks on every re-embed is worse than one that is merely stale.
//   - it is auditable: an operator can read why an image matched a query.
//   - it survives an embedder swap. Re-embedding then costs one vector operation
//     instead of a vision call per image, which over thousands of images is the
//     difference between a re-embed being routine and being a budget decision.

import (
	"context"
	"strings"
	"time"

	"github.com/denn-gubsky/loomcycle/internal/sqlmem"
)

// assetDescription reads a chunk's persisted vision description, or "" when there
// is none — no asset, no describe pass yet, or a pass that produced nothing.
//
// BEST-EFFORT BY DESIGN. A store fault returns "" rather than an error because the
// only caller is on the embed path, where the alternative is worse: failing the
// read would either fail an author's write over a missing description, or embed the
// caption while pretending no description exists. Returning "" degrades to
// exactly the phase-4a behaviour — caption-only — which is a correct index, just a
// less complete one.
func (d *Document) assetDescription(ctx context.Context, key sqlmem.ScopeKey, chunkID string) string {
	if d.SqlMem == nil {
		return ""
	}
	res, err := d.query(ctx, key, `SELECT description FROM chunk_assets WHERE chunk_id = ? LIMIT 1`, chunkID)
	if err != nil || len(res.Rows) == 0 || len(res.Rows[0]) == 0 {
		return ""
	}
	return strings.TrimSpace(asStr(res.Rows[0][0]))
}

// assetDescriptionState reads the description AND whether a pass has run, which
// get_asset needs in order to report the three states apart. at == 0 means no
// describe pass has examined this image.
func (d *Document) assetDescriptionState(ctx context.Context, key sqlmem.ScopeKey, chunkID string) (description string, at int64) {
	if d.SqlMem == nil {
		return "", 0
	}
	res, err := d.query(ctx, key,
		`SELECT description, described_at FROM chunk_assets WHERE chunk_id = ? LIMIT 1`, chunkID)
	if err != nil || len(res.Rows) == 0 || len(res.Rows[0]) < 2 {
		return "", 0
	}
	return strings.TrimSpace(asStr(res.Rows[0][0])), int64(asInt(res.Rows[0][1]))
}

// setAssetDescription persists a generated description next to the asset bytes.
//
// described_at is stamped even for an EMPTY description, which is the point of
// having it as a separate column: "a model looked and produced nothing useful" and
// "nothing has looked yet" are different states, and a sweep that cannot tell them
// apart re-describes the same unproductive image on every run.
func (d *Document) setAssetDescription(ctx context.Context, key sqlmem.ScopeKey, chunkID, description string) error {
	return d.exec(ctx, key,
		`UPDATE chunk_assets SET description = ?, described_at = ? WHERE chunk_id = ?`,
		strings.TrimSpace(description), time.Now().UnixNano(), chunkID)
}

// imageEmbedText composes the searchable text for an image chunk.
//
// Returns "" when there is nothing to index — no caption and no description yet.
// The caller then stores no vector at all, which is the honest state: the image is
// unsearchable but not lost, and it becomes searchable when a describe pass fills
// the description in. Embedding a placeholder would be worse than embedding
// nothing, because a row that exists ranks against every query.
func imageEmbedText(caption, description string) string {
	caption = strings.TrimSpace(caption)
	description = strings.TrimSpace(description)
	// A data URI is not a caption. An image chunk can transiently hold the rendered
	// markdown form as its body (an import that has not yet had its bytes split out
	// into chunk_assets), and embedding base64 indexes nothing while consuming the
	// scope's vector quota.
	if typ, _, _, _ := classifyMediaBody(caption); typ == "image" {
		caption = ""
	}
	parts := make([]string, 0, 3)
	if caption != "" {
		parts = append(parts, caption)
	}
	// Appended, not substituted. A caption is what the author chose to say and a
	// description is what a model saw; either alone can be the one that matches, so
	// dropping one to avoid duplication would trade recall for tidiness.
	if description != "" && !strings.EqualFold(description, caption) {
		parts = append(parts, description)
	}
	if len(parts) == 0 {
		return ""
	}
	// "image" is prefixed for the same reason the mermaid extractor names the
	// diagram kind: it is itself a useful query term when someone is looking for a
	// picture of something rather than prose about it.
	return "image: " + strings.Join(parts, " ")
}
