// loomcycle's gRPC service surface (v0.5.5).
//
// Mirrors the existing HTTP+SSE wire shape exactly — every RPC has a
// 1:1 mapping to an HTTP route under /v1/. Both wire surfaces coexist
// on the same loomcycle process; operators pick one (or both) via
// LOOMCYCLE_GRPC_ADDR / LOOMCYCLE_LISTEN_ADDR.
//
// Compatibility:
//   - The HTTP+SSE surface is the canonical contract for now.
//     Anything that ships there must be expressible here without
//     loss; proto changes follow HTTP+SSE, not the other way.
//   - Field numbers are stable across v0.5.x. Adding a new field is
//     non-breaking; removing or renumbering one is. v0 caveats apply
//     until v1.0 is tagged.
//   - The `status` strings use the same enum the HTTP API uses
//     (running / completed / failed / cancelled) — represented as
//     proto strings, not a typed enum, so adding a new state on the
//     HTTP side doesn't require regenerating gRPC stubs everywhere.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: loomcycle.proto

package loomcyclepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Loomcycle_Run_FullMethodName            = "/loomcycle.v1.Loomcycle/Run"
	Loomcycle_Continue_FullMethodName       = "/loomcycle.v1.Loomcycle/Continue"
	Loomcycle_GetTranscript_FullMethodName  = "/loomcycle.v1.Loomcycle/GetTranscript"
	Loomcycle_GetAgent_FullMethodName       = "/loomcycle.v1.Loomcycle/GetAgent"
	Loomcycle_CancelAgent_FullMethodName    = "/loomcycle.v1.Loomcycle/CancelAgent"
	Loomcycle_ListUserAgents_FullMethodName = "/loomcycle.v1.Loomcycle/ListUserAgents"
	Loomcycle_Health_FullMethodName         = "/loomcycle.v1.Loomcycle/Health"
	Loomcycle_RegisterHook_FullMethodName   = "/loomcycle.v1.Loomcycle/RegisterHook"
	Loomcycle_ListHooks_FullMethodName      = "/loomcycle.v1.Loomcycle/ListHooks"
	Loomcycle_DeleteHook_FullMethodName     = "/loomcycle.v1.Loomcycle/DeleteHook"
)

// LoomcycleClient is the client API for Loomcycle service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LoomcycleClient interface {
	// Run starts a fresh agent run and server-streams its events. One
	// request → many Event responses. The stream terminates on EOF when
	// the loop reaches its terminal state (done, failed, or cancelled).
	//
	// Mirrors POST /v1/runs.
	Run(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error)
	// Continue extends an existing session with a new run. The session's
	// prior transcript is replayed into the loop's context; the response
	// stream covers only the NEW events from this continuation.
	//
	// Mirrors POST /v1/sessions/{id}/messages.
	Continue(ctx context.Context, in *ContinueRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error)
	// GetTranscript returns the full event history for a session,
	// ordered by seq. Used by adapters that re-attach to a previously
	// started session (e.g. cross-tab sync).
	//
	// Mirrors GET /v1/sessions/{id}/transcript.
	GetTranscript(ctx context.Context, in *GetTranscriptRequest, opts ...grpc.CallOption) (*Transcript, error)
	// GetAgent returns one agent's current status + usage stats. Used
	// by adapters polling for completion when the SSE/gRPC stream was
	// interrupted (browser tab closed, network blip).
	//
	// Mirrors GET /v1/agents/{agent_id}.
	GetAgent(ctx context.Context, in *GetAgentRequest, opts ...grpc.CallOption) (*Agent, error)
	// CancelAgent sets the agent's terminal status to "cancelled" and
	// cascades the cancellation to every child via parent_agent_id.
	//
	// Mirrors POST /v1/agents/{agent_id}/cancel.
	CancelAgent(ctx context.Context, in *CancelAgentRequest, opts ...grpc.CallOption) (*CancelAgentResponse, error)
	// ListUserAgents enumerates a user's recent agent runs, optionally
	// filtered by status.
	//
	// Mirrors GET /v1/users/{user_id}/agents.
	ListUserAgents(ctx context.Context, in *ListUserAgentsRequest, opts ...grpc.CallOption) (*ListUserAgentsResponse, error)
	// Health is the liveness probe. Returns build identifier + uptime.
	//
	// Mirrors GET /healthz (which is unauthenticated on the HTTP side;
	// the gRPC equivalent stays unauthenticated for parity).
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	// RegisterHook registers a pre- or post-tool webhook. The
	// callback_url must be an http:// or https:// endpoint the consumer
	// runs. Returns the loomcycle-assigned id. Re-registering the same
	// (owner, name) replaces the prior entry in-place (idempotent on
	// app restart).
	//
	// Mirrors POST /v1/hooks.
	RegisterHook(ctx context.Context, in *RegisterHookRequest, opts ...grpc.CallOption) (*RegisterHookResponse, error)
	// ListHooks returns every currently-registered hook. Useful for
	// debug; no pagination — the registry is intentionally small
	// (operator-curated set).
	//
	// Mirrors GET /v1/hooks.
	ListHooks(ctx context.Context, in *ListHooksRequest, opts ...grpc.CallOption) (*ListHooksResponse, error)
	// DeleteHook removes a registered hook by id. Returns
	// codes.NotFound when no hook has that id.
	//
	// Mirrors DELETE /v1/hooks/{id}.
	DeleteHook(ctx context.Context, in *DeleteHookRequest, opts ...grpc.CallOption) (*DeleteHookResponse, error)
}

type loomcycleClient struct {
	cc grpc.ClientConnInterface
}

func NewLoomcycleClient(cc grpc.ClientConnInterface) LoomcycleClient {
	return &loomcycleClient{cc}
}

func (c *loomcycleClient) Run(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Loomcycle_ServiceDesc.Streams[0], Loomcycle_Run_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RunRequest, Event]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Loomcycle_RunClient = grpc.ServerStreamingClient[Event]

func (c *loomcycleClient) Continue(ctx context.Context, in *ContinueRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Loomcycle_ServiceDesc.Streams[1], Loomcycle_Continue_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ContinueRequest, Event]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Loomcycle_ContinueClient = grpc.ServerStreamingClient[Event]

func (c *loomcycleClient) GetTranscript(ctx context.Context, in *GetTranscriptRequest, opts ...grpc.CallOption) (*Transcript, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Transcript)
	err := c.cc.Invoke(ctx, Loomcycle_GetTranscript_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loomcycleClient) GetAgent(ctx context.Context, in *GetAgentRequest, opts ...grpc.CallOption) (*Agent, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Agent)
	err := c.cc.Invoke(ctx, Loomcycle_GetAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loomcycleClient) CancelAgent(ctx context.Context, in *CancelAgentRequest, opts ...grpc.CallOption) (*CancelAgentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelAgentResponse)
	err := c.cc.Invoke(ctx, Loomcycle_CancelAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loomcycleClient) ListUserAgents(ctx context.Context, in *ListUserAgentsRequest, opts ...grpc.CallOption) (*ListUserAgentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListUserAgentsResponse)
	err := c.cc.Invoke(ctx, Loomcycle_ListUserAgents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loomcycleClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, Loomcycle_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loomcycleClient) RegisterHook(ctx context.Context, in *RegisterHookRequest, opts ...grpc.CallOption) (*RegisterHookResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterHookResponse)
	err := c.cc.Invoke(ctx, Loomcycle_RegisterHook_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loomcycleClient) ListHooks(ctx context.Context, in *ListHooksRequest, opts ...grpc.CallOption) (*ListHooksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListHooksResponse)
	err := c.cc.Invoke(ctx, Loomcycle_ListHooks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loomcycleClient) DeleteHook(ctx context.Context, in *DeleteHookRequest, opts ...grpc.CallOption) (*DeleteHookResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteHookResponse)
	err := c.cc.Invoke(ctx, Loomcycle_DeleteHook_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LoomcycleServer is the server API for Loomcycle service.
// All implementations must embed UnimplementedLoomcycleServer
// for forward compatibility.
type LoomcycleServer interface {
	// Run starts a fresh agent run and server-streams its events. One
	// request → many Event responses. The stream terminates on EOF when
	// the loop reaches its terminal state (done, failed, or cancelled).
	//
	// Mirrors POST /v1/runs.
	Run(*RunRequest, grpc.ServerStreamingServer[Event]) error
	// Continue extends an existing session with a new run. The session's
	// prior transcript is replayed into the loop's context; the response
	// stream covers only the NEW events from this continuation.
	//
	// Mirrors POST /v1/sessions/{id}/messages.
	Continue(*ContinueRequest, grpc.ServerStreamingServer[Event]) error
	// GetTranscript returns the full event history for a session,
	// ordered by seq. Used by adapters that re-attach to a previously
	// started session (e.g. cross-tab sync).
	//
	// Mirrors GET /v1/sessions/{id}/transcript.
	GetTranscript(context.Context, *GetTranscriptRequest) (*Transcript, error)
	// GetAgent returns one agent's current status + usage stats. Used
	// by adapters polling for completion when the SSE/gRPC stream was
	// interrupted (browser tab closed, network blip).
	//
	// Mirrors GET /v1/agents/{agent_id}.
	GetAgent(context.Context, *GetAgentRequest) (*Agent, error)
	// CancelAgent sets the agent's terminal status to "cancelled" and
	// cascades the cancellation to every child via parent_agent_id.
	//
	// Mirrors POST /v1/agents/{agent_id}/cancel.
	CancelAgent(context.Context, *CancelAgentRequest) (*CancelAgentResponse, error)
	// ListUserAgents enumerates a user's recent agent runs, optionally
	// filtered by status.
	//
	// Mirrors GET /v1/users/{user_id}/agents.
	ListUserAgents(context.Context, *ListUserAgentsRequest) (*ListUserAgentsResponse, error)
	// Health is the liveness probe. Returns build identifier + uptime.
	//
	// Mirrors GET /healthz (which is unauthenticated on the HTTP side;
	// the gRPC equivalent stays unauthenticated for parity).
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	// RegisterHook registers a pre- or post-tool webhook. The
	// callback_url must be an http:// or https:// endpoint the consumer
	// runs. Returns the loomcycle-assigned id. Re-registering the same
	// (owner, name) replaces the prior entry in-place (idempotent on
	// app restart).
	//
	// Mirrors POST /v1/hooks.
	RegisterHook(context.Context, *RegisterHookRequest) (*RegisterHookResponse, error)
	// ListHooks returns every currently-registered hook. Useful for
	// debug; no pagination — the registry is intentionally small
	// (operator-curated set).
	//
	// Mirrors GET /v1/hooks.
	ListHooks(context.Context, *ListHooksRequest) (*ListHooksResponse, error)
	// DeleteHook removes a registered hook by id. Returns
	// codes.NotFound when no hook has that id.
	//
	// Mirrors DELETE /v1/hooks/{id}.
	DeleteHook(context.Context, *DeleteHookRequest) (*DeleteHookResponse, error)
	mustEmbedUnimplementedLoomcycleServer()
}

// UnimplementedLoomcycleServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLoomcycleServer struct{}

func (UnimplementedLoomcycleServer) Run(*RunRequest, grpc.ServerStreamingServer[Event]) error {
	return status.Error(codes.Unimplemented, "method Run not implemented")
}
func (UnimplementedLoomcycleServer) Continue(*ContinueRequest, grpc.ServerStreamingServer[Event]) error {
	return status.Error(codes.Unimplemented, "method Continue not implemented")
}
func (UnimplementedLoomcycleServer) GetTranscript(context.Context, *GetTranscriptRequest) (*Transcript, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTranscript not implemented")
}
func (UnimplementedLoomcycleServer) GetAgent(context.Context, *GetAgentRequest) (*Agent, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAgent not implemented")
}
func (UnimplementedLoomcycleServer) CancelAgent(context.Context, *CancelAgentRequest) (*CancelAgentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelAgent not implemented")
}
func (UnimplementedLoomcycleServer) ListUserAgents(context.Context, *ListUserAgentsRequest) (*ListUserAgentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListUserAgents not implemented")
}
func (UnimplementedLoomcycleServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedLoomcycleServer) RegisterHook(context.Context, *RegisterHookRequest) (*RegisterHookResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterHook not implemented")
}
func (UnimplementedLoomcycleServer) ListHooks(context.Context, *ListHooksRequest) (*ListHooksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListHooks not implemented")
}
func (UnimplementedLoomcycleServer) DeleteHook(context.Context, *DeleteHookRequest) (*DeleteHookResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteHook not implemented")
}
func (UnimplementedLoomcycleServer) mustEmbedUnimplementedLoomcycleServer() {}
func (UnimplementedLoomcycleServer) testEmbeddedByValue()                   {}

// UnsafeLoomcycleServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LoomcycleServer will
// result in compilation errors.
type UnsafeLoomcycleServer interface {
	mustEmbedUnimplementedLoomcycleServer()
}

func RegisterLoomcycleServer(s grpc.ServiceRegistrar, srv LoomcycleServer) {
	// If the following call panics, it indicates UnimplementedLoomcycleServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Loomcycle_ServiceDesc, srv)
}

func _Loomcycle_Run_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RunRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LoomcycleServer).Run(m, &grpc.GenericServerStream[RunRequest, Event]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Loomcycle_RunServer = grpc.ServerStreamingServer[Event]

func _Loomcycle_Continue_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ContinueRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LoomcycleServer).Continue(m, &grpc.GenericServerStream[ContinueRequest, Event]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Loomcycle_ContinueServer = grpc.ServerStreamingServer[Event]

func _Loomcycle_GetTranscript_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTranscriptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoomcycleServer).GetTranscript(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Loomcycle_GetTranscript_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoomcycleServer).GetTranscript(ctx, req.(*GetTranscriptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Loomcycle_GetAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoomcycleServer).GetAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Loomcycle_GetAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoomcycleServer).GetAgent(ctx, req.(*GetAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Loomcycle_CancelAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoomcycleServer).CancelAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Loomcycle_CancelAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoomcycleServer).CancelAgent(ctx, req.(*CancelAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Loomcycle_ListUserAgents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUserAgentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoomcycleServer).ListUserAgents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Loomcycle_ListUserAgents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoomcycleServer).ListUserAgents(ctx, req.(*ListUserAgentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Loomcycle_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoomcycleServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Loomcycle_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoomcycleServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Loomcycle_RegisterHook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterHookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoomcycleServer).RegisterHook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Loomcycle_RegisterHook_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoomcycleServer).RegisterHook(ctx, req.(*RegisterHookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Loomcycle_ListHooks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListHooksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoomcycleServer).ListHooks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Loomcycle_ListHooks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoomcycleServer).ListHooks(ctx, req.(*ListHooksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Loomcycle_DeleteHook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteHookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoomcycleServer).DeleteHook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Loomcycle_DeleteHook_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoomcycleServer).DeleteHook(ctx, req.(*DeleteHookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Loomcycle_ServiceDesc is the grpc.ServiceDesc for Loomcycle service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Loomcycle_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "loomcycle.v1.Loomcycle",
	HandlerType: (*LoomcycleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTranscript",
			Handler:    _Loomcycle_GetTranscript_Handler,
		},
		{
			MethodName: "GetAgent",
			Handler:    _Loomcycle_GetAgent_Handler,
		},
		{
			MethodName: "CancelAgent",
			Handler:    _Loomcycle_CancelAgent_Handler,
		},
		{
			MethodName: "ListUserAgents",
			Handler:    _Loomcycle_ListUserAgents_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _Loomcycle_Health_Handler,
		},
		{
			MethodName: "RegisterHook",
			Handler:    _Loomcycle_RegisterHook_Handler,
		},
		{
			MethodName: "ListHooks",
			Handler:    _Loomcycle_ListHooks_Handler,
		},
		{
			MethodName: "DeleteHook",
			Handler:    _Loomcycle_DeleteHook_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Run",
			Handler:       _Loomcycle_Run_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Continue",
			Handler:       _Loomcycle_Continue_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "loomcycle.proto",
}
