// loomcycle's gRPC service surface (v0.5.5).
//
// Mirrors the existing HTTP+SSE wire shape exactly — every RPC has a
// 1:1 mapping to an HTTP route under /v1/. Both wire surfaces coexist
// on the same loomcycle process; operators pick one (or both) via
// LOOMCYCLE_GRPC_ADDR / LOOMCYCLE_LISTEN_ADDR.
//
// Compatibility:
//   - The HTTP+SSE surface is the canonical contract for now.
//     Anything that ships there must be expressible here without
//     loss; proto changes follow HTTP+SSE, not the other way.
//   - Field numbers are stable across v0.5.x. Adding a new field is
//     non-breaking; removing or renumbering one is. v0 caveats apply
//     until v1.0 is tagged.
//   - The `status` strings use the same enum the HTTP API uses
//     (running / completed / failed / cancelled) — represented as
//     proto strings, not a typed enum, so adding a new state on the
//     HTTP side doesn't require regenerating gRPC stubs everywhere.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: loomcycle.proto

package loomcyclepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RunRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Agent name from the operator yaml's agents block.
	Agent string `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	// Session ID. Empty → start a fresh session; non-empty → continue
	// the named session (transcript replayed before the new turn).
	// The HTTP equivalent is "set the session_id field on POST /v1/runs".
	SessionId string `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Prompt content blocks (system + user mix). Empty → use the
	// operator-configured agent system_prompt only.
	Segments []*PromptSegment `protobuf:"bytes,3,rep,name=segments,proto3" json:"segments,omitempty"`
	// Per-call tool allowlist, intersected with the agent's allowed_tools.
	// Empty → no narrowing (agent's full tool surface).
	AllowedTools []string `protobuf:"bytes,4,rep,name=allowed_tools,json=allowedTools,proto3" json:"allowed_tools,omitempty"`
	// Per-call host allowlist for HTTP / WebFetch / WebSearch.
	// Three states (proto3 doesn't support nullable repeated, so we use
	// a wrapper):
	//   - allowed_hosts unset (oneof not selected) — no narrowing
	//   - allowed_hosts.list = [] — deny all (no host reachable)
	//   - allowed_hosts.list = [...] — intersection with operator's list
	AllowedHosts *HostAllowlist `protobuf:"bytes,5,opt,name=allowed_hosts,json=allowedHosts,proto3" json:"allowed_hosts,omitempty"`
	// WebSearch result-narrowing mode. Ignored when allowed_hosts is
	// unset. "drop" (default) filters out non-allowed results;
	// "keep" returns the full set.
	WebSearchFilter string `protobuf:"bytes,6,opt,name=web_search_filter,json=webSearchFilter,proto3" json:"web_search_filter,omitempty"`
	// v0.4+ tracking fields. agent_id is the caller-supplied tracking
	// handle (for cross-process status polls). user_id binds the run
	// to a user for ListUserAgents + cancel-cascade.
	AgentId       string `protobuf:"bytes,7,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	UserId        string `protobuf:"bytes,8,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunRequest) Reset() {
	*x = RunRequest{}
	mi := &file_loomcycle_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunRequest) ProtoMessage() {}

func (x *RunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_loomcycle_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunRequest.ProtoReflect.Descriptor instead.
func (*RunRequest) Descriptor() ([]byte, []int) {
	return file_loomcycle_proto_rawDescGZIP(), []int{0}
}

func (x *RunRequest) GetAgent() string {
	if x != nil {
		return x.Agent
	}
	return ""
}

func (x *RunRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RunRequest) GetSegments() []*PromptSegment {
	if x != nil {
		return x.Segments
	}
	return nil
}

func (x *RunRequest) GetAllowedTools() []string {
	if x != nil {
		return x.AllowedTools
	}
	return nil
}

func (x *RunRequest) GetAllowedHosts() *HostAllowlist {
	if x != nil {
		return x.AllowedHosts
	}
	return nil
}

func (x *RunRequest) GetWebSearchFilter() string {
	if x != nil {
		return x.WebSearchFilter
	}
	return ""
}

func (x *RunRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *RunRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ContinueRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SessionId       string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Segments        []*PromptSegment       `protobuf:"bytes,2,rep,name=segments,proto3" json:"segments,omitempty"`
	AllowedTools    []string               `protobuf:"bytes,3,rep,name=allowed_tools,json=allowedTools,proto3" json:"allowed_tools,omitempty"`
	AllowedHosts    *HostAllowlist         `protobuf:"bytes,4,opt,name=allowed_hosts,json=allowedHosts,proto3" json:"allowed_hosts,omitempty"`
	WebSearchFilter string                 `protobuf:"bytes,5,opt,name=web_search_filter,json=webSearchFilter,proto3" json:"web_search_filter,omitempty"`
	AgentId         string                 `protobuf:"bytes,6,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"` // fresh tracking handle for this continuation
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ContinueRequest) Reset() {
	*x = ContinueRequest{}
	mi := &file_loomcycle_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContinueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContinueRequest) ProtoMessage() {}

func (x *ContinueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_loomcycle_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContinueRequest.ProtoReflect.Descriptor instead.
func (*ContinueRequest) Descriptor() ([]byte, []int) {
	return file_loomcycle_proto_rawDescGZIP(), []int{1}
}

func (x *ContinueRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ContinueRequest) GetSegments() []*PromptSegment {
	if x != nil {
		return x.Segments
	}
	return nil
}

func (x *ContinueRequest) GetAllowedTools() []string {
	if x != nil {
		return x.AllowedTools
	}
	return nil
}

func (x *ContinueRequest) GetAllowedHosts() *HostAllowlist {
	if x != nil {
		return x.AllowedHosts
	}
	return nil
}

func (x *ContinueRequest) GetWebSearchFilter() string {
	if x != nil {
		return x.WebSearchFilter
	}
	return ""
}

func (x *ContinueRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

// HostAllowlist wraps a repeated string so the absence-of-list state
// is distinguishable from the empty-list state on the wire.
type HostAllowlist struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []string               `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostAllowlist) Reset() {
	*x = HostAllowlist{}
	mi := &file_loomcycle_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostAllowlist) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostAllowlist) ProtoMessage() {}

func (x *HostAllowlist) ProtoReflect() protoreflect.Message {
	mi := &file_loomcycle_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostAllowlist.ProtoReflect.Descriptor instead.
func (*HostAllowlist) Descriptor() ([]byte, []int) {
	return file_loomcycle_proto_rawDescGZIP(), []int{2}
}

func (x *HostAllowlist) GetList() []string {
	if x != nil {
		return x.List
	}
	return nil
}

// PromptSegment mirrors loop.PromptSegment. Role is "system" | "user"
// | "assistant"; in practice, gRPC callers send only "system" and
// "user" segments and let the loop produce "assistant" turns.
type PromptSegment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Content       []*PromptContentBlock  `protobuf:"bytes,2,rep,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PromptSegment) Reset() {
	*x = PromptSegment{}
	mi := &file_loomcycle_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromptSegment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromptSegment) ProtoMessage() {}

func (x *PromptSegment) ProtoReflect() protoreflect.Message {
	mi := &file_loomcycle_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromptSegment.ProtoReflect.Descriptor instead.
func (*PromptSegment) Descriptor() ([]byte, []int) {
	return file_loomcycle_proto_rawDescGZIP(), []int{3}
}

func (x *PromptSegment) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *PromptSegment) GetContent() []*PromptContentBlock {
	if x != nil {
		return x.Content
	}
	return nil
}

// PromptContentBlock mirrors loop.PromptContentBlock. The trust
// vocabulary stays HTTP-compatible:
//   - "trusted-text" / "user-text" / "tool-output-text" / "third-party-text"
//
// Cacheable=true marks this block for native provider caching
// (Anthropic cache_control). Ignored on providers that don't support it.
type PromptContentBlock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Cacheable     bool                   `protobuf:"varint,3,opt,name=cacheable,proto3" json:"cacheable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PromptContentBlock) Reset() {
	*x = PromptContentBlock{}
	mi := &file_loomcycle_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromptContentBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromptContentBlock) ProtoMessage() {}

func (x *PromptContentBlock) ProtoReflect() protoreflect.Message {
	mi := &file_loomcycle_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromptContentBlock.ProtoReflect.Descriptor instead.
func (*PromptContentBlock) Descriptor() ([]byte, []int) {
	return file_loomcycle_proto_rawDescGZIP(), []int{4}
}

func (x *PromptContentBlock) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PromptContentBlock) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *PromptContentBlock) GetCacheable() bool {
	if x != nil {
		return x.Cacheable
	}
	return false
}

// Event is one frame on the Run/Continue server stream. Mirrors
// providers.Event 1:1 — fields stay nullable (proto3 message-type
// fields default to nil-equivalent) so the wire shape can carry
// "this event is just text" or "this event is a tool_use" or "this
// event is a usage update" without per-type subclassing.
type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // text | tool_use | tool_result | usage | retry | done | error
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	ToolUse       *ToolUse               `protobuf:"bytes,3,opt,name=tool_use,json=toolUse,proto3" json:"tool_use,omitempty"`
	Usage         *Usage                 `protobuf:"bytes,4,opt,name=usage,proto3" json:"usage,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	IsError       bool                   `protobuf:"varint,6,opt,name=is_error,json=isError,proto3" json:"is_error,omitempty"` // tool_result with execution failure
	Retry         *Retry                 `protobuf:"bytes,7,opt,name=retry,proto3" json:"retry,omitempty"`
	StopReason    string                 `protobuf:"bytes,8,opt,name=stop_reason,json=stopReason,proto3" json:"stop_reason,omitempty"` // end_turn | tool_use | max_tokens | stop_sequence
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_loomcycle_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_loomcycle_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_loomcycle_proto_rawDescGZIP(), []int{5}
}

func (x *Event) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Event) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Event) GetToolUse() *ToolUse {
	if x != nil {
		return x.ToolUse
	}
	return nil
}

func (x *Event) GetUsage() *Usage {
	if x != nil {
		return x.Usage
	}
	return nil
}

func (x *Event) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *Event) GetIsError() bool {
	if x != nil {
		return x.IsError
	}
	return false
}

func (x *Event) GetRetry() *Retry {
	if x != nil {
		return x.Retry
	}
	return nil
}

func (x *Event) GetStopReason() string {
	if x != nil {
		return x.StopReason
	}
	return ""
}

// ToolUse carries one tool_use block emitted by the model. The id is
// the model's correlator (Claude tu_*, OpenAI call_*); name is the
// tool's registered name; input is the raw JSON the model produced.
type ToolUse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Input         []byte                 `protobuf:"bytes,3,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolUse) Reset() {
	*x = ToolUse{}
	mi := &file_loomcycle_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolUse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolUse) ProtoMessage() {}

func (x *ToolUse) ProtoReflect() protoreflect.Message {
	mi := &file_loomcycle_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolUse.ProtoReflect.Descriptor instead.
func (*ToolUse) Descriptor() ([]byte, []int) {
	return file_loomcycle_proto_rawDescGZIP(), []int{6}
}

func (x *ToolUse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ToolUse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolUse) GetInput() []byte {
	if x != nil {
		return x.Input
	}
	return nil
}

// Usage is the per-call token accounting. CacheCreation/Read tokens
// surface on Anthropic provider responses; zero on others.
type Usage struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	InputTokens         int64                  `protobuf:"varint,1,opt,name=input_tokens,json=inputTokens,proto3" json:"input_tokens,omitempty"`
	OutputTokens        int64                  `protobuf:"varint,2,opt,name=output_tokens,json=outputTokens,proto3" json:"output_tokens,omitempty"`
	CacheCreationTokens int64                  `protobuf:"varint,3,opt,name=cache_creation_tokens,json=cacheCreationTokens,proto3" json:"cache_creation_tokens,omitempty"`
	CacheReadTokens     int64                  `protobuf:"varint,4,opt,name=cache_read_tokens,json=cacheReadTokens,proto3" json:"cache_read_tokens,omitempty"`
	Model               string                 `protobuf:"bytes,5,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Usage) Reset() {
	*x = Usage{}
	mi := &file_loomcycle_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Usage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Usage) ProtoMessage() {}

func (x *Usage) ProtoReflect() protoreflect.Message {
	mi := &file_loomcycle_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Usage.ProtoReflect.Descriptor instead.
func (*Usage) Descriptor() ([]byte, []int) {
	return file_loomcycle_proto_rawDescGZIP(), []int{7}
}

func (x *Usage) GetInputTokens() int64 {
	if x != nil {
		return x.InputTokens
	}
	return 0
}

func (x *Usage) GetOutputTokens() int64 {
	if x != nil {
		return x.OutputTokens
	}
	return 0
}

func (x *Usage) GetCacheCreationTokens() int64 {
	if x != nil {
		return x.CacheCreationTokens
	}
	return 0
}

func (x *Usage) GetCacheReadTokens() int64 {
	if x != nil {
		return x.CacheReadTokens
	}
	return 0
}

func (x *Usage) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

// Retry mirrors providers.RetryInfo. Fired when a provider 429 is
// being retried with backoff; gives adapters live "waiting on rate
// limit" telemetry.
type Retry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Attempt       int32                  `protobuf:"varint,2,opt,name=attempt,proto3" json:"attempt,omitempty"`
	WaitMs        int64                  `protobuf:"varint,3,opt,name=wait_ms,json=waitMs,proto3" json:"wait_ms,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"` // RetryReasonHeader | RetryReasonSchedule
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Retry) Reset() {
	*x = Retry{}
	mi := &file_loomcycle_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Retry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Retry) ProtoMessage() {}

func (x *Retry) ProtoReflect() protoreflect.Message {
	mi := &file_loomcycle_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Retry.ProtoReflect.Descriptor instead.
func (*Retry) Descriptor() ([]byte, []int) {
	return file_loomcycle_proto_rawDescGZIP(), []int{8}
}

func (x *Retry) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *Retry) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *Retry) GetWaitMs() int64 {
	if x != nil {
		return x.WaitMs
	}
	return 0
}

func (x *Retry) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type GetTranscriptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTranscriptRequest) Reset() {
	*x = GetTranscriptRequest{}
	mi := &file_loomcycle_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTranscriptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTranscriptRequest) ProtoMessage() {}

func (x *GetTranscriptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_loomcycle_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTranscriptRequest.ProtoReflect.Descriptor instead.
func (*GetTranscriptRequest) Descriptor() ([]byte, []int) {
	return file_loomcycle_proto_rawDescGZIP(), []int{9}
}

func (x *GetTranscriptRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type Transcript struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*TranscriptEvent     `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transcript) Reset() {
	*x = Transcript{}
	mi := &file_loomcycle_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transcript) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transcript) ProtoMessage() {}

func (x *Transcript) ProtoReflect() protoreflect.Message {
	mi := &file_loomcycle_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transcript.ProtoReflect.Descriptor instead.
func (*Transcript) Descriptor() ([]byte, []int) {
	return file_loomcycle_proto_rawDescGZIP(), []int{10}
}

func (x *Transcript) GetEvents() []*TranscriptEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

// TranscriptEvent is one persisted store.Event. The payload is raw
// JSON bytes (matching the HTTP transcript surface) so adapters
// decode the same way regardless of wire choice.
type TranscriptEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seq           int64                  `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	RunId         string                 `protobuf:"bytes,3,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Ts            *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=ts,proto3" json:"ts,omitempty"`
	Type          string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,6,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranscriptEvent) Reset() {
	*x = TranscriptEvent{}
	mi := &file_loomcycle_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranscriptEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranscriptEvent) ProtoMessage() {}

func (x *TranscriptEvent) ProtoReflect() protoreflect.Message {
	mi := &file_loomcycle_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranscriptEvent.ProtoReflect.Descriptor instead.
func (*TranscriptEvent) Descriptor() ([]byte, []int) {
	return file_loomcycle_proto_rawDescGZIP(), []int{11}
}

func (x *TranscriptEvent) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *TranscriptEvent) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *TranscriptEvent) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *TranscriptEvent) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *TranscriptEvent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *TranscriptEvent) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type GetAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentRequest) Reset() {
	*x = GetAgentRequest{}
	mi := &file_loomcycle_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentRequest) ProtoMessage() {}

func (x *GetAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_loomcycle_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentRequest.ProtoReflect.Descriptor instead.
func (*GetAgentRequest) Descriptor() ([]byte, []int) {
	return file_loomcycle_proto_rawDescGZIP(), []int{12}
}

func (x *GetAgentRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

// Agent mirrors HTTP's agentResponse. Status is a string (running |
// completed | failed | cancelled) so the wire stays compatible with
// future status additions without regen.
type Agent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AgentId         string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	RunId           string                 `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	SessionId       string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	UserId          string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ParentAgentId   string                 `protobuf:"bytes,5,opt,name=parent_agent_id,json=parentAgentId,proto3" json:"parent_agent_id,omitempty"`
	Status          string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	StartedAt       *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	StopReason      string                 `protobuf:"bytes,9,opt,name=stop_reason,json=stopReason,proto3" json:"stop_reason,omitempty"`
	Error           string                 `protobuf:"bytes,10,opt,name=error,proto3" json:"error,omitempty"`
	Usage           *AgentUsage            `protobuf:"bytes,11,opt,name=usage,proto3" json:"usage,omitempty"`
	LastHeartbeatAt *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=last_heartbeat_at,json=lastHeartbeatAt,proto3" json:"last_heartbeat_at,omitempty"`
	// Live = true when the agent is still in the cancel registry (i.e.
	// cancellable). Adapters use this to distinguish "running and
	// cancellable" from "running per the row but the registry doesn't
	// know about it" (process restart leaves the latter).
	Live          bool `protobuf:"varint,13,opt,name=live,proto3" json:"live,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Agent) Reset() {
	*x = Agent{}
	mi := &file_loomcycle_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Agent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Agent) ProtoMessage() {}

func (x *Agent) ProtoReflect() protoreflect.Message {
	mi := &file_loomcycle_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Agent.ProtoReflect.Descriptor instead.
func (*Agent) Descriptor() ([]byte, []int) {
	return file_loomcycle_proto_rawDescGZIP(), []int{13}
}

func (x *Agent) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *Agent) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *Agent) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Agent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Agent) GetParentAgentId() string {
	if x != nil {
		return x.ParentAgentId
	}
	return ""
}

func (x *Agent) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Agent) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *Agent) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

func (x *Agent) GetStopReason() string {
	if x != nil {
		return x.StopReason
	}
	return ""
}

func (x *Agent) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *Agent) GetUsage() *AgentUsage {
	if x != nil {
		return x.Usage
	}
	return nil
}

func (x *Agent) GetLastHeartbeatAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastHeartbeatAt
	}
	return nil
}

func (x *Agent) GetLive() bool {
	if x != nil {
		return x.Live
	}
	return false
}

// AgentUsage mirrors agentResponseUsage.
type AgentUsage struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	InputTokens         int64                  `protobuf:"varint,1,opt,name=input_tokens,json=inputTokens,proto3" json:"input_tokens,omitempty"`
	OutputTokens        int64                  `protobuf:"varint,2,opt,name=output_tokens,json=outputTokens,proto3" json:"output_tokens,omitempty"`
	CacheCreationTokens int64                  `protobuf:"varint,3,opt,name=cache_creation_tokens,json=cacheCreationTokens,proto3" json:"cache_creation_tokens,omitempty"`
	CacheReadTokens     int64                  `protobuf:"varint,4,opt,name=cache_read_tokens,json=cacheReadTokens,proto3" json:"cache_read_tokens,omitempty"`
	Model               string                 `protobuf:"bytes,5,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *AgentUsage) Reset() {
	*x = AgentUsage{}
	mi := &file_loomcycle_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentUsage) ProtoMessage() {}

func (x *AgentUsage) ProtoReflect() protoreflect.Message {
	mi := &file_loomcycle_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentUsage.ProtoReflect.Descriptor instead.
func (*AgentUsage) Descriptor() ([]byte, []int) {
	return file_loomcycle_proto_rawDescGZIP(), []int{14}
}

func (x *AgentUsage) GetInputTokens() int64 {
	if x != nil {
		return x.InputTokens
	}
	return 0
}

func (x *AgentUsage) GetOutputTokens() int64 {
	if x != nil {
		return x.OutputTokens
	}
	return 0
}

func (x *AgentUsage) GetCacheCreationTokens() int64 {
	if x != nil {
		return x.CacheCreationTokens
	}
	return 0
}

func (x *AgentUsage) GetCacheReadTokens() int64 {
	if x != nil {
		return x.CacheReadTokens
	}
	return 0
}

func (x *AgentUsage) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

type CancelAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelAgentRequest) Reset() {
	*x = CancelAgentRequest{}
	mi := &file_loomcycle_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelAgentRequest) ProtoMessage() {}

func (x *CancelAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_loomcycle_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelAgentRequest.ProtoReflect.Descriptor instead.
func (*CancelAgentRequest) Descriptor() ([]byte, []int) {
	return file_loomcycle_proto_rawDescGZIP(), []int{15}
}

func (x *CancelAgentRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *CancelAgentRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type CancelAgentResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// cancelled_count is the number of agents (this one plus any
	// descendants reached via parent_agent_id walk) marked cancelled.
	CancelledCount int32 `protobuf:"varint,1,opt,name=cancelled_count,json=cancelledCount,proto3" json:"cancelled_count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CancelAgentResponse) Reset() {
	*x = CancelAgentResponse{}
	mi := &file_loomcycle_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelAgentResponse) ProtoMessage() {}

func (x *CancelAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_loomcycle_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelAgentResponse.ProtoReflect.Descriptor instead.
func (*CancelAgentResponse) Descriptor() ([]byte, []int) {
	return file_loomcycle_proto_rawDescGZIP(), []int{16}
}

func (x *CancelAgentResponse) GetCancelledCount() int32 {
	if x != nil {
		return x.CancelledCount
	}
	return 0
}

type ListUserAgentsRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	UserId string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Optional status filter ("running" | "completed" | "failed" |
	// "cancelled"). Empty → all statuses.
	Status        string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserAgentsRequest) Reset() {
	*x = ListUserAgentsRequest{}
	mi := &file_loomcycle_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserAgentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserAgentsRequest) ProtoMessage() {}

func (x *ListUserAgentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_loomcycle_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserAgentsRequest.ProtoReflect.Descriptor instead.
func (*ListUserAgentsRequest) Descriptor() ([]byte, []int) {
	return file_loomcycle_proto_rawDescGZIP(), []int{17}
}

func (x *ListUserAgentsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListUserAgentsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ListUserAgentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agents        []*Agent               `protobuf:"bytes,1,rep,name=agents,proto3" json:"agents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserAgentsResponse) Reset() {
	*x = ListUserAgentsResponse{}
	mi := &file_loomcycle_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserAgentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserAgentsResponse) ProtoMessage() {}

func (x *ListUserAgentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_loomcycle_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserAgentsResponse.ProtoReflect.Descriptor instead.
func (*ListUserAgentsResponse) Descriptor() ([]byte, []int) {
	return file_loomcycle_proto_rawDescGZIP(), []int{18}
}

func (x *ListUserAgentsResponse) GetAgents() []*Agent {
	if x != nil {
		return x.Agents
	}
	return nil
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_loomcycle_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_loomcycle_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_loomcycle_proto_rawDescGZIP(), []int{19}
}

type HealthResponse struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Ok     bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Commit string                 `protobuf:"bytes,2,opt,name=commit,proto3" json:"commit,omitempty"`
	Built  string                 `protobuf:"bytes,3,opt,name=built,proto3" json:"built,omitempty"`
	// Uptime in seconds since process start.
	UptimeSeconds int64 `protobuf:"varint,4,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_loomcycle_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_loomcycle_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_loomcycle_proto_rawDescGZIP(), []int{20}
}

func (x *HealthResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *HealthResponse) GetCommit() string {
	if x != nil {
		return x.Commit
	}
	return ""
}

func (x *HealthResponse) GetBuilt() string {
	if x != nil {
		return x.Built
	}
	return ""
}

func (x *HealthResponse) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

var File_loomcycle_proto protoreflect.FileDescriptor

const file_loomcycle_proto_rawDesc = "" +
	"\n" +
	"\x0floomcycle.proto\x12\floomcycle.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc1\x02\n" +
	"\n" +
	"RunRequest\x12\x14\n" +
	"\x05agent\x18\x01 \x01(\tR\x05agent\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x127\n" +
	"\bsegments\x18\x03 \x03(\v2\x1b.loomcycle.v1.PromptSegmentR\bsegments\x12#\n" +
	"\rallowed_tools\x18\x04 \x03(\tR\fallowedTools\x12@\n" +
	"\rallowed_hosts\x18\x05 \x01(\v2\x1b.loomcycle.v1.HostAllowlistR\fallowedHosts\x12*\n" +
	"\x11web_search_filter\x18\x06 \x01(\tR\x0fwebSearchFilter\x12\x19\n" +
	"\bagent_id\x18\a \x01(\tR\aagentId\x12\x17\n" +
	"\auser_id\x18\b \x01(\tR\x06userId\"\x97\x02\n" +
	"\x0fContinueRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x127\n" +
	"\bsegments\x18\x02 \x03(\v2\x1b.loomcycle.v1.PromptSegmentR\bsegments\x12#\n" +
	"\rallowed_tools\x18\x03 \x03(\tR\fallowedTools\x12@\n" +
	"\rallowed_hosts\x18\x04 \x01(\v2\x1b.loomcycle.v1.HostAllowlistR\fallowedHosts\x12*\n" +
	"\x11web_search_filter\x18\x05 \x01(\tR\x0fwebSearchFilter\x12\x19\n" +
	"\bagent_id\x18\x06 \x01(\tR\aagentId\"#\n" +
	"\rHostAllowlist\x12\x12\n" +
	"\x04list\x18\x01 \x03(\tR\x04list\"_\n" +
	"\rPromptSegment\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12:\n" +
	"\acontent\x18\x02 \x03(\v2 .loomcycle.v1.PromptContentBlockR\acontent\"Z\n" +
	"\x12PromptContentBlock\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x1c\n" +
	"\tcacheable\x18\x03 \x01(\bR\tcacheable\"\x89\x02\n" +
	"\x05Event\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x120\n" +
	"\btool_use\x18\x03 \x01(\v2\x15.loomcycle.v1.ToolUseR\atoolUse\x12)\n" +
	"\x05usage\x18\x04 \x01(\v2\x13.loomcycle.v1.UsageR\x05usage\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\x12\x19\n" +
	"\bis_error\x18\x06 \x01(\bR\aisError\x12)\n" +
	"\x05retry\x18\a \x01(\v2\x13.loomcycle.v1.RetryR\x05retry\x12\x1f\n" +
	"\vstop_reason\x18\b \x01(\tR\n" +
	"stopReason\"C\n" +
	"\aToolUse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05input\x18\x03 \x01(\fR\x05input\"\xc5\x01\n" +
	"\x05Usage\x12!\n" +
	"\finput_tokens\x18\x01 \x01(\x03R\vinputTokens\x12#\n" +
	"\routput_tokens\x18\x02 \x01(\x03R\foutputTokens\x122\n" +
	"\x15cache_creation_tokens\x18\x03 \x01(\x03R\x13cacheCreationTokens\x12*\n" +
	"\x11cache_read_tokens\x18\x04 \x01(\x03R\x0fcacheReadTokens\x12\x14\n" +
	"\x05model\x18\x05 \x01(\tR\x05model\"n\n" +
	"\x05Retry\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x18\n" +
	"\aattempt\x18\x02 \x01(\x05R\aattempt\x12\x17\n" +
	"\await_ms\x18\x03 \x01(\x03R\x06waitMs\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"5\n" +
	"\x14GetTranscriptRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"C\n" +
	"\n" +
	"Transcript\x125\n" +
	"\x06events\x18\x01 \x03(\v2\x1d.loomcycle.v1.TranscriptEventR\x06events\"\xb3\x01\n" +
	"\x0fTranscriptEvent\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x03R\x03seq\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x15\n" +
	"\x06run_id\x18\x03 \x01(\tR\x05runId\x12*\n" +
	"\x02ts\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x02ts\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\x12\x18\n" +
	"\apayload\x18\x06 \x01(\fR\apayload\",\n" +
	"\x0fGetAgentRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"\xee\x03\n" +
	"\x05Agent\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\x12&\n" +
	"\x0fparent_agent_id\x18\x05 \x01(\tR\rparentAgentId\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x129\n" +
	"\n" +
	"started_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12=\n" +
	"\fcompleted_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\x12\x1f\n" +
	"\vstop_reason\x18\t \x01(\tR\n" +
	"stopReason\x12\x14\n" +
	"\x05error\x18\n" +
	" \x01(\tR\x05error\x12.\n" +
	"\x05usage\x18\v \x01(\v2\x18.loomcycle.v1.AgentUsageR\x05usage\x12F\n" +
	"\x11last_heartbeat_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\x0flastHeartbeatAt\x12\x12\n" +
	"\x04live\x18\r \x01(\bR\x04live\"\xca\x01\n" +
	"\n" +
	"AgentUsage\x12!\n" +
	"\finput_tokens\x18\x01 \x01(\x03R\vinputTokens\x12#\n" +
	"\routput_tokens\x18\x02 \x01(\x03R\foutputTokens\x122\n" +
	"\x15cache_creation_tokens\x18\x03 \x01(\x03R\x13cacheCreationTokens\x12*\n" +
	"\x11cache_read_tokens\x18\x04 \x01(\x03R\x0fcacheReadTokens\x12\x14\n" +
	"\x05model\x18\x05 \x01(\tR\x05model\"G\n" +
	"\x12CancelAgentRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\">\n" +
	"\x13CancelAgentResponse\x12'\n" +
	"\x0fcancelled_count\x18\x01 \x01(\x05R\x0ecancelledCount\"H\n" +
	"\x15ListUserAgentsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"E\n" +
	"\x16ListUserAgentsResponse\x12+\n" +
	"\x06agents\x18\x01 \x03(\v2\x13.loomcycle.v1.AgentR\x06agents\"\x0f\n" +
	"\rHealthRequest\"u\n" +
	"\x0eHealthResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x16\n" +
	"\x06commit\x18\x02 \x01(\tR\x06commit\x12\x14\n" +
	"\x05built\x18\x03 \x01(\tR\x05built\x12%\n" +
	"\x0euptime_seconds\x18\x04 \x01(\x03R\ruptimeSeconds2\x8a\x04\n" +
	"\tLoomcycle\x126\n" +
	"\x03Run\x12\x18.loomcycle.v1.RunRequest\x1a\x13.loomcycle.v1.Event0\x01\x12@\n" +
	"\bContinue\x12\x1d.loomcycle.v1.ContinueRequest\x1a\x13.loomcycle.v1.Event0\x01\x12M\n" +
	"\rGetTranscript\x12\".loomcycle.v1.GetTranscriptRequest\x1a\x18.loomcycle.v1.Transcript\x12>\n" +
	"\bGetAgent\x12\x1d.loomcycle.v1.GetAgentRequest\x1a\x13.loomcycle.v1.Agent\x12R\n" +
	"\vCancelAgent\x12 .loomcycle.v1.CancelAgentRequest\x1a!.loomcycle.v1.CancelAgentResponse\x12[\n" +
	"\x0eListUserAgents\x12#.loomcycle.v1.ListUserAgentsRequest\x1a$.loomcycle.v1.ListUserAgentsResponse\x12C\n" +
	"\x06Health\x12\x1b.loomcycle.v1.HealthRequest\x1a\x1c.loomcycle.v1.HealthResponseBLZJgithub.com/denn-gubsky/loomcycle/internal/api/grpc/loomcyclepb;loomcyclepbb\x06proto3"

var (
	file_loomcycle_proto_rawDescOnce sync.Once
	file_loomcycle_proto_rawDescData []byte
)

func file_loomcycle_proto_rawDescGZIP() []byte {
	file_loomcycle_proto_rawDescOnce.Do(func() {
		file_loomcycle_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_loomcycle_proto_rawDesc), len(file_loomcycle_proto_rawDesc)))
	})
	return file_loomcycle_proto_rawDescData
}

var file_loomcycle_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_loomcycle_proto_goTypes = []any{
	(*RunRequest)(nil),             // 0: loomcycle.v1.RunRequest
	(*ContinueRequest)(nil),        // 1: loomcycle.v1.ContinueRequest
	(*HostAllowlist)(nil),          // 2: loomcycle.v1.HostAllowlist
	(*PromptSegment)(nil),          // 3: loomcycle.v1.PromptSegment
	(*PromptContentBlock)(nil),     // 4: loomcycle.v1.PromptContentBlock
	(*Event)(nil),                  // 5: loomcycle.v1.Event
	(*ToolUse)(nil),                // 6: loomcycle.v1.ToolUse
	(*Usage)(nil),                  // 7: loomcycle.v1.Usage
	(*Retry)(nil),                  // 8: loomcycle.v1.Retry
	(*GetTranscriptRequest)(nil),   // 9: loomcycle.v1.GetTranscriptRequest
	(*Transcript)(nil),             // 10: loomcycle.v1.Transcript
	(*TranscriptEvent)(nil),        // 11: loomcycle.v1.TranscriptEvent
	(*GetAgentRequest)(nil),        // 12: loomcycle.v1.GetAgentRequest
	(*Agent)(nil),                  // 13: loomcycle.v1.Agent
	(*AgentUsage)(nil),             // 14: loomcycle.v1.AgentUsage
	(*CancelAgentRequest)(nil),     // 15: loomcycle.v1.CancelAgentRequest
	(*CancelAgentResponse)(nil),    // 16: loomcycle.v1.CancelAgentResponse
	(*ListUserAgentsRequest)(nil),  // 17: loomcycle.v1.ListUserAgentsRequest
	(*ListUserAgentsResponse)(nil), // 18: loomcycle.v1.ListUserAgentsResponse
	(*HealthRequest)(nil),          // 19: loomcycle.v1.HealthRequest
	(*HealthResponse)(nil),         // 20: loomcycle.v1.HealthResponse
	(*timestamppb.Timestamp)(nil),  // 21: google.protobuf.Timestamp
}
var file_loomcycle_proto_depIdxs = []int32{
	3,  // 0: loomcycle.v1.RunRequest.segments:type_name -> loomcycle.v1.PromptSegment
	2,  // 1: loomcycle.v1.RunRequest.allowed_hosts:type_name -> loomcycle.v1.HostAllowlist
	3,  // 2: loomcycle.v1.ContinueRequest.segments:type_name -> loomcycle.v1.PromptSegment
	2,  // 3: loomcycle.v1.ContinueRequest.allowed_hosts:type_name -> loomcycle.v1.HostAllowlist
	4,  // 4: loomcycle.v1.PromptSegment.content:type_name -> loomcycle.v1.PromptContentBlock
	6,  // 5: loomcycle.v1.Event.tool_use:type_name -> loomcycle.v1.ToolUse
	7,  // 6: loomcycle.v1.Event.usage:type_name -> loomcycle.v1.Usage
	8,  // 7: loomcycle.v1.Event.retry:type_name -> loomcycle.v1.Retry
	11, // 8: loomcycle.v1.Transcript.events:type_name -> loomcycle.v1.TranscriptEvent
	21, // 9: loomcycle.v1.TranscriptEvent.ts:type_name -> google.protobuf.Timestamp
	21, // 10: loomcycle.v1.Agent.started_at:type_name -> google.protobuf.Timestamp
	21, // 11: loomcycle.v1.Agent.completed_at:type_name -> google.protobuf.Timestamp
	14, // 12: loomcycle.v1.Agent.usage:type_name -> loomcycle.v1.AgentUsage
	21, // 13: loomcycle.v1.Agent.last_heartbeat_at:type_name -> google.protobuf.Timestamp
	13, // 14: loomcycle.v1.ListUserAgentsResponse.agents:type_name -> loomcycle.v1.Agent
	0,  // 15: loomcycle.v1.Loomcycle.Run:input_type -> loomcycle.v1.RunRequest
	1,  // 16: loomcycle.v1.Loomcycle.Continue:input_type -> loomcycle.v1.ContinueRequest
	9,  // 17: loomcycle.v1.Loomcycle.GetTranscript:input_type -> loomcycle.v1.GetTranscriptRequest
	12, // 18: loomcycle.v1.Loomcycle.GetAgent:input_type -> loomcycle.v1.GetAgentRequest
	15, // 19: loomcycle.v1.Loomcycle.CancelAgent:input_type -> loomcycle.v1.CancelAgentRequest
	17, // 20: loomcycle.v1.Loomcycle.ListUserAgents:input_type -> loomcycle.v1.ListUserAgentsRequest
	19, // 21: loomcycle.v1.Loomcycle.Health:input_type -> loomcycle.v1.HealthRequest
	5,  // 22: loomcycle.v1.Loomcycle.Run:output_type -> loomcycle.v1.Event
	5,  // 23: loomcycle.v1.Loomcycle.Continue:output_type -> loomcycle.v1.Event
	10, // 24: loomcycle.v1.Loomcycle.GetTranscript:output_type -> loomcycle.v1.Transcript
	13, // 25: loomcycle.v1.Loomcycle.GetAgent:output_type -> loomcycle.v1.Agent
	16, // 26: loomcycle.v1.Loomcycle.CancelAgent:output_type -> loomcycle.v1.CancelAgentResponse
	18, // 27: loomcycle.v1.Loomcycle.ListUserAgents:output_type -> loomcycle.v1.ListUserAgentsResponse
	20, // 28: loomcycle.v1.Loomcycle.Health:output_type -> loomcycle.v1.HealthResponse
	22, // [22:29] is the sub-list for method output_type
	15, // [15:22] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_loomcycle_proto_init() }
func file_loomcycle_proto_init() {
	if File_loomcycle_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_loomcycle_proto_rawDesc), len(file_loomcycle_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_loomcycle_proto_goTypes,
		DependencyIndexes: file_loomcycle_proto_depIdxs,
		MessageInfos:      file_loomcycle_proto_msgTypes,
	}.Build()
	File_loomcycle_proto = out.File
	file_loomcycle_proto_goTypes = nil
	file_loomcycle_proto_depIdxs = nil
}
